export interface LangQuestion {
  id: string
  question: string
  options: string[]
  correct: number
  explanation: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  topic: string
}

export const LANGUAGE_QUESTIONS: Record<string, LangQuestion[]> = {

  javascript: [
    { id: 'js-1', difficulty: 'Easy', topic: 'Closures', question: 'What does a closure capture?', options: ['Only the value of variables at the time the closure was created', 'A reference to the outer scope — live variables, not snapshots', 'A copy of the entire outer function', 'Nothing — closures have their own isolated scope'], correct: 1, explanation: 'A closure captures a reference to its enclosing scope, not a snapshot. If the outer variable changes after the closure is created, the closure sees the updated value.' },
    { id: 'js-2', difficulty: 'Easy', topic: 'Event loop', question: 'What is the output order of: console.log("A"); setTimeout(()=>console.log("B"),0); Promise.resolve().then(()=>console.log("C")); console.log("D")?', options: ['A B C D', 'A D C B', 'A D B C', 'D A C B'], correct: 1, explanation: 'Synchronous code (A, D) runs first. Microtasks (Promise .then → C) drain before macrotasks (setTimeout → B). Output: A D C B.' },
    { id: 'js-3', difficulty: 'Medium', topic: 'Prototype chain', question: 'What does Object.create(null) produce?', options: ['A null value', 'An object with no prototype — no toString, hasOwnProperty, or any inherited methods', 'An error — create requires an object argument', 'An empty class instance'], correct: 1, explanation: 'Object.create(null) creates an object with a [[Prototype]] of null. It inherits nothing from Object.prototype — useful for pure dictionaries with no prototype pollution risk.' },
    { id: 'js-4', difficulty: 'Medium', topic: 'Promises', question: 'What happens if you throw an error inside a Promise executor that has no catch handler?', options: ['The error is silently swallowed', 'The Promise rejects — the error becomes the rejection reason. Unhandled, it triggers an unhandledRejection event', 'The process crashes immediately', 'The error propagates to the calling function synchronously'], correct: 1, explanation: 'Throwing inside a Promise executor auto-rejects the promise. Without a .catch(), it becomes an unhandled rejection — Node.js can terminate the process; browsers log a warning.' },
    { id: 'js-5', difficulty: 'Easy', topic: 'ES6+', question: 'What does the optional chaining operator (?.) return when the left-hand side is null or undefined?', options: ['Throws a TypeError', 'Returns null', 'Returns undefined without throwing', 'Returns false'], correct: 2, explanation: 'Optional chaining short-circuits and returns undefined when the left-hand side is null or undefined, preventing the "Cannot read property of null" TypeError.' },
    { id: 'js-6', difficulty: 'Hard', topic: 'Event loop', question: 'Which task queue has higher priority — microtask queue (Promises) or macrotask queue (setTimeout)?', options: ['Macrotask — it was introduced first', 'They have equal priority, processed in FIFO order', 'Microtask — the entire microtask queue drains after each task before the next macrotask runs', 'It depends on the JavaScript engine'], correct: 2, explanation: 'After each macrotask (script, setTimeout, setInterval), the JS engine drains ALL microtasks (Promise .then, queueMicrotask, MutationObserver) before picking the next macrotask. Microtasks always run before the next macrotask.' },
    { id: 'js-7', difficulty: 'Medium', topic: 'Closures', question: 'The classic loop closure bug: for (var i = 0; i < 3; i++) { setTimeout(() => console.log(i), 0) }. What gets logged?', options: ['0 1 2', '3 3 3 — all callbacks capture the same var i which equals 3 by then', '0 0 0', 'undefined undefined undefined'], correct: 1, explanation: 'var is function-scoped, not block-scoped. All three callbacks share the same i. By the time they execute, the loop has finished and i === 3. Fix: use let (block-scoped) or an IIFE to capture the current value.' },
    { id: 'js-8', difficulty: 'Easy', topic: 'Types', question: 'What does typeof null return in JavaScript?', options: ['"null"', '"undefined"', '"object" — a historical bug in the language', '"number"'], correct: 2, explanation: 'typeof null === "object" is a well-known JavaScript bug that has never been fixed for backward compatibility. null is not an object — use === null to check for null.' },
    { id: 'js-9', difficulty: 'Hard', topic: 'Async', question: 'What is the difference between Promise.all and Promise.allSettled?', options: ['They are identical', 'Promise.all rejects immediately if any promise rejects. Promise.allSettled waits for all to settle and returns an array of {status, value/reason} objects', 'Promise.allSettled is faster', 'Promise.all returns an array of results; Promise.allSettled returns a single result'], correct: 1, explanation: 'Promise.all short-circuits on the first rejection — you lose results from already-resolved promises. Promise.allSettled always waits for all promises and gives you both fulfilled and rejected outcomes, ideal when you need all results regardless of failures.' },
    { id: 'js-10', difficulty: 'Medium', topic: 'Scope', question: 'What is the difference between var, let, and const regarding hoisting?', options: ['None — all three are hoisted identically', 'var is hoisted and initialized to undefined; let and const are hoisted but not initialized (temporal dead zone) — accessing them before declaration throws a ReferenceError', 'Only var is hoisted; let and const are not hoisted at all', 'const is not hoisted; var and let are'], correct: 1, explanation: 'All three are hoisted to the top of their scope. var is initialized to undefined immediately. let and const enter the Temporal Dead Zone (TDZ) — they exist in scope but cannot be accessed until the declaration is reached, throwing a ReferenceError if you try.' },
  ],

  typescript: [
    { id: 'ts-1', difficulty: 'Easy', topic: 'Types', question: 'What is the key difference between type and interface in TypeScript?', options: ['type is for primitives; interface is for objects', 'interface can be extended with declaration merging; type aliases cannot be re-opened. Types are more flexible for unions and mapped types', 'They are completely identical', 'type is faster at compilation; interface is slower'], correct: 1, explanation: 'interface supports declaration merging (multiple declarations with the same name merge) and is better for OOP patterns. type supports union types, intersection types, and mapped types more expressively. Both can describe object shapes.' },
    { id: 'ts-2', difficulty: 'Medium', topic: 'Generics', question: 'What does <T extends object> constrain in a generic function?', options: ['T must be a class instance', 'T must be a non-null, non-primitive value — objects, arrays, functions are allowed; string, number, boolean are not', 'T must have at least one property', 'T must be JSON-serializable'], correct: 1, explanation: 'extends object constrains T to non-primitive types. Primitives (string, number, boolean, symbol, bigint, null, undefined) are excluded. Object types, arrays, and function types satisfy this constraint.' },
    { id: 'ts-3', difficulty: 'Medium', topic: 'Utility types', question: 'What does Partial<T> do?', options: ['Makes all properties of T readonly', 'Makes all properties of T optional (?)', 'Makes all properties of T required', 'Picks specific properties from T'], correct: 1, explanation: 'Partial<T> creates a new type where all properties of T are made optional (each gets a ? modifier). Useful for update payloads where only some fields are provided.' },
    { id: 'ts-4', difficulty: 'Hard', topic: 'Type narrowing', question: 'What is a type predicate and when would you use one?', options: ['A way to cast a type forcefully using "as"', 'A function return type like "value is SomeType" that tells the type checker the argument is narrowed to that type inside the true branch of an if', 'A generic constraint that filters union types', 'A decorator that validates types at runtime'], correct: 1, explanation: 'A type predicate (paramName is Type) in a function\'s return type tells TypeScript that if the function returns true, the parameter has been narrowed to the specified type. Used in user-defined type guards: function isString(x: unknown): x is string { return typeof x === "string" }' },
    { id: 'ts-5', difficulty: 'Easy', topic: 'Strictness', question: 'What does the "strict" tsconfig option enable?', options: ['Only strictNullChecks', 'A bundle of strict checks: strictNullChecks, strictFunctionTypes, strictPropertyInitialization, noImplicitAny, and others', 'Only noImplicitAny', 'It makes TypeScript throw errors at runtime'], correct: 1, explanation: '"strict: true" is a shorthand that enables several strict type-checking flags simultaneously, most importantly strictNullChecks (null/undefined are not assignable to other types without explicit handling) and noImplicitAny.' },
    { id: 'ts-6', difficulty: 'Medium', topic: 'Mapped types', question: 'What does Record<K, V> represent?', options: ['An array of key-value pairs', 'An object type with keys of type K and values of type V', 'A Map data structure', 'A dictionary with string keys only'], correct: 1, explanation: 'Record<K, V> is equivalent to { [key in K]: V }. It creates an object type where every key is a member of K and every value is V. Common use: Record<string, number> for a string-keyed numeric map.' },
    { id: 'ts-7', difficulty: 'Hard', topic: 'Generics', question: 'What is the infer keyword used for inside conditional types?', options: ['It infers the TypeScript version to use', 'It captures a type within a conditional type expression — you can extract sub-types like function return types or array element types', 'It automatically infers generic type parameters at the call site', 'It is deprecated in TypeScript 5+'], correct: 1, explanation: 'infer is only valid inside conditional types (T extends ... ? ... : ...). It introduces a type variable that TypeScript infers from the matched pattern. Example: type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never extracts the return type of a function.' },
    { id: 'ts-8', difficulty: 'Easy', topic: 'Types', question: 'What is the difference between unknown and any?', options: ['They are identical', 'any disables type checking completely. unknown is type-safe — you must narrow or assert before using it', 'unknown can only hold primitive values', 'any is for runtime values; unknown is for compile-time only'], correct: 1, explanation: 'any opts out of type checking entirely — you can do anything to an any value. unknown is the type-safe counterpart — you can assign any value to it, but you cannot use it without first narrowing (typeof check, type guard) or asserting its type.' },
    { id: 'ts-9', difficulty: 'Medium', topic: 'Declaration files', question: 'What is a .d.ts file?', options: ['A TypeScript file that is compiled to JavaScript', 'A declaration file containing only type information — no runtime code. Used to provide types for JavaScript libraries', 'A debug type script file', 'A TypeScript configuration file'], correct: 1, explanation: '.d.ts files contain only type declarations (no implementation). They describe the shape of JavaScript modules so TypeScript can type-check code that uses them. @types/react, for example, ships .d.ts files for the React library.' },
    { id: 'ts-10', difficulty: 'Hard', topic: 'Utility types', question: 'What does ReturnType<typeof fn> give you?', options: ['The type of the function fn itself', 'The return type of function fn, inferred at compile time without calling it', 'The parameter types of fn as a tuple', 'The async resolved type of fn'], correct: 1, explanation: 'ReturnType<T> extracts the return type from a function type. Combined with typeof, you get the return type of a specific function without manually declaring it — useful when the function\'s return type is complex or inferred.' },
  ],

  react: [
    { id: 'react-1', difficulty: 'Easy', topic: 'Hooks', question: 'When does useEffect run?', options: ['Before the component renders', 'After every render by default; the dependency array controls when it re-runs', 'Only once when the component mounts, regardless of deps', 'Synchronously during the render phase'], correct: 1, explanation: 'useEffect runs after the browser has painted. With no dependency array it runs after every render. With [] it runs once on mount. With [dep] it runs when dep changes. It always runs after the first render.' },
    { id: 'react-2', difficulty: 'Medium', topic: 'Performance', question: 'When should you use useMemo vs useCallback?', options: ['They are interchangeable', 'useMemo memoizes a computed value; useCallback memoizes a function reference. Use useMemo for expensive computations, useCallback to stabilize function references passed to child components or used in deps', 'useCallback is for async functions; useMemo is for sync', 'useMemo is deprecated — always use useCallback'], correct: 1, explanation: 'useMemo(() => compute(a, b), [a, b]) caches the computed result and recomputes only when deps change. useCallback(fn, [deps]) caches the function reference itself — prevents child re-renders when the function is passed as a prop.' },
    { id: 'react-3', difficulty: 'Hard', topic: 'Reconciliation', question: 'What is the "key" prop used for in React lists, and what happens if you use an array index as the key?', options: ['key is just a display label with no functional purpose', 'key identifies elements across renders for reconciliation. Using array index causes incorrect updates/animations when items are added/removed/reordered — React may reuse DOM nodes for the wrong items', 'key must be globally unique across the entire app', 'key controls the render order of list items'], correct: 1, explanation: 'React uses key to match elements between renders. Stable keys (e.g., item.id) tell React which element changed. Index keys break when the list is mutated: removing item 0 shifts all indices, so React incorrectly reuses the DOM node from item 0 for item 1.' },
    { id: 'react-4', difficulty: 'Easy', topic: 'State', question: 'Why must you never mutate state directly in React?', options: ['React will throw an error if you do', 'React uses shallow equality comparison to detect state changes. Mutating the same object reference means the reference doesn\'t change, so React doesn\'t re-render', 'Direct mutation is slower than setState', 'useState only works with immutable data structures'], correct: 1, explanation: 'useState batches state updates and compares old vs new state by reference. If you mutate the current state object, the reference stays the same — React sees no change and skips re-rendering. Always create a new object/array: setState({...state, field: value}).' },
    { id: 'react-5', difficulty: 'Medium', topic: 'Context', question: 'What is a common performance problem with React Context and how do you fix it?', options: ['Context is inherently slower than props', 'Every component that consumes the context re-renders when any context value changes, even if it only uses one part of it. Fix: split contexts by concern, or use selectors with state management libraries', 'Context causes memory leaks', 'Context only works one level deep'], correct: 1, explanation: 'When a context value changes, all consuming components re-render. If your context holds a large object, changing one field re-renders all consumers. Solutions: split into smaller contexts, use useMemo to stabilize the value, or use Zustand/Redux for granular subscriptions.' },
    { id: 'react-6', difficulty: 'Hard', topic: 'Hooks', question: 'What is the stale closure problem in React hooks?', options: ['A closure that references a deleted component', 'When a hook\'s closure captures an old value of a state or prop and never updates — common with useEffect and event listeners that close over stale values', 'Memory leaks caused by forgetting to clean up effects', 'An error thrown when calling hooks conditionally'], correct: 1, explanation: 'A stale closure occurs when a function (e.g., inside useEffect) captures state/props from its creation render and doesn\'t see later updates. Fix: include the value in the dependency array (re-creates the effect with fresh values) or use useRef to hold a mutable reference to the latest value.' },
    { id: 'react-7', difficulty: 'Easy', topic: 'Lifecycle', question: 'What does the cleanup function returned from useEffect do?', options: ['It prevents the component from unmounting', 'It runs before the effect re-runs (on dep change) and when the component unmounts — used to cancel subscriptions, clear timers, abort fetches', 'It reverses the DOM changes made by the effect', 'It is called synchronously before the render'], correct: 1, explanation: 'The function returned from useEffect is the cleanup function. React calls it before re-running the effect (when deps change) and on unmount. Use it to cancel event listeners, clear setInterval, abort fetch requests, or unsubscribe from observables to prevent memory leaks.' },
    { id: 'react-8', difficulty: 'Medium', topic: 'Performance', question: 'What is the difference between React.memo and useMemo?', options: ['They are the same thing', 'React.memo wraps a component and prevents re-renders if props are shallowly equal. useMemo memoizes a value inside a component', 'React.memo is for class components; useMemo is for function components', 'Both memoize values but React.memo is deprecated'], correct: 1, explanation: 'React.memo is a higher-order component: React.memo(MyComp) skips re-rendering MyComp if its props haven\'t changed (shallow comparison). useMemo is a hook that caches a computed value within a render — not related to preventing component re-renders.' },
    { id: 'react-9', difficulty: 'Hard', topic: 'Fiber', question: 'What problem did React Fiber (React 16) solve?', options: ['It added TypeScript support to React', 'The old stack-based reconciler was synchronous and couldn\'t be interrupted — Fiber made reconciliation incremental and interruptible, enabling features like Suspense, Concurrent Mode, and priority scheduling', 'Fiber replaced class components with function components', 'Fiber improved the Context API performance'], correct: 1, explanation: 'Before Fiber, the reconciler recursively processed the entire tree synchronously — it couldn\'t pause and resume, causing frame drops on large updates. Fiber represents work units that can be paused, aborted, or reused. This enables time-slicing, Suspense, and concurrent features in React 18+.' },
    { id: 'react-10', difficulty: 'Medium', topic: 'Patterns', question: 'When would you use useReducer instead of useState?', options: ['useReducer is always better than useState', 'When state logic is complex (multiple sub-values, next state depends on previous in non-trivial ways), or when you have multiple actions that update state in related ways — reducer centralizes the update logic', 'useReducer is for async state; useState is for sync', 'useState cannot handle objects; useReducer can'], correct: 1, explanation: 'useReducer shines when: (1) state is an object with multiple fields that update together, (2) the next state depends on the previous in complex ways, (3) update logic is shared across handlers. It co-locates update logic and makes state transitions explicit.' },
  ],

  python: [
    { id: 'py-1', difficulty: 'Easy', topic: 'Functions', question: 'What is the difference between *args and **kwargs in a Python function signature?', options: ['They are identical', '*args collects extra positional arguments as a tuple; **kwargs collects extra keyword arguments as a dict', '*args is for strings; **kwargs is for numbers', '**kwargs must come before *args'], correct: 1, explanation: '*args captures any number of positional arguments beyond named params into a tuple. **kwargs captures keyword arguments into a dict. Order: positional, *args, keyword-only, **kwargs.' },
    { id: 'py-2', difficulty: 'Medium', topic: 'Decorators', question: 'What does a decorator do in Python?', options: ['It adds CSS-like styling to terminal output', 'It wraps a function/class with another function, adding behavior before or after (or instead of) the original without modifying its source code', 'It marks a function as deprecated', 'It compiles a function to native code for speed'], correct: 1, explanation: 'A decorator is syntactic sugar for: func = decorator(func). It replaces the original function with the wrapper. Common uses: logging, timing, access control, caching (@functools.lru_cache), retry logic.' },
    { id: 'py-3', difficulty: 'Medium', topic: 'Generators', question: 'What is the advantage of a generator over returning a list?', options: ['Generators are always faster', 'Generators produce values lazily on demand — they use O(1) memory regardless of the sequence length, unlike a list that materializes all values at once', 'Generators are easier to write', 'Generators run in parallel automatically'], correct: 1, explanation: 'A generator yields values one at a time with yield, suspending execution between calls. Processing 1 billion rows one at a time uses constant memory. A list of 1B items would exhaust RAM. Generators are ideal for pipelines and large data streams.' },
    { id: 'py-4', difficulty: 'Hard', topic: 'GIL', question: 'What is Python\'s GIL and when does it limit performance?', options: ['A global error handler for Python programs', 'The Global Interpreter Lock prevents multiple threads from executing Python bytecode simultaneously. It limits CPU-bound multi-threaded programs — use multiprocessing or async I/O instead', 'A garbage collection mechanism unique to Python', 'A lock that prevents concurrent file I/O'], correct: 1, explanation: 'The GIL ensures only one thread runs Python bytecode at a time, protecting CPython\'s reference counting. CPU-bound threads don\'t benefit from multi-threading (use multiprocessing). I/O-bound threads are fine — the GIL is released during blocking I/O calls.' },
    { id: 'py-5', difficulty: 'Easy', topic: 'OOP', question: 'What does __init__ do and what is self?', options: ['__init__ is called when the module imports; self is the module reference', '__init__ is the constructor — called when a new instance is created. self is a reference to the current instance, automatically passed as the first argument to instance methods', '__init__ is a static method; self is a class variable', '__init__ runs once per class; self is a global variable'], correct: 1, explanation: '__init__ initialises a new instance\'s attributes. self (conventionally named, but just the first parameter) refers to the instance being created. Python passes it automatically — you don\'t provide it when calling: obj = MyClass() calls __init__(obj).' },
    { id: 'py-6', difficulty: 'Medium', topic: 'Memory', question: 'How does Python\'s reference counting work and what problem can it cause?', options: ['Python uses a tracing garbage collector only; no reference counting', 'Every object tracks how many references point to it. When count hits 0, the object is freed. Problem: circular references (A→B→A) never reach 0 — Python\'s cyclic GC detects and cleans these up', 'Reference counting only applies to primitive types', 'Python uses a generational GC with no reference counting'], correct: 1, explanation: 'CPython uses reference counting as the primary memory management. Each object has a refcount; dropping to 0 frees it immediately and deterministically. Circular references (obj A holds a reference to obj B which holds a reference back to A) prevent either from ever reaching 0 — the cyclic garbage collector (gc module) handles these.' },
    { id: 'py-7', difficulty: 'Easy', topic: 'Comprehensions', question: 'What is the difference between [x for x in range(10)] and (x for x in range(10))?', options: ['They are identical — square vs round brackets make no difference', 'Square brackets create a list (materialised in memory immediately). Round brackets create a generator expression (lazy, evaluates on demand)', 'Round brackets create a tuple', 'Square brackets are for sets; round brackets for lists'], correct: 1, explanation: 'List comprehension [...] eagerly evaluates and stores all elements in memory. Generator expression (...) creates a lazy iterator — each value is computed only when requested. Generator expressions are memory-efficient for large or infinite sequences.' },
    { id: 'py-8', difficulty: 'Hard', topic: 'Async', question: 'What is the difference between asyncio.gather and asyncio.wait?', options: ['They are identical', 'gather runs all awaitables concurrently and returns results in the same order; it cancels all on first exception (by default). wait is lower-level and lets you act as tasks complete or on first exception/completion', 'gather is for I/O; wait is for CPU tasks', 'wait is deprecated in Python 3.11+'], correct: 1, explanation: 'asyncio.gather(*coros) is the high-level API: runs concurrently, returns results in input order, raises on first exception. asyncio.wait(tasks, return_when=...) is lower-level: returns sets of done/pending tasks and gives you control over partial completion and cancellation.' },
    { id: 'py-9', difficulty: 'Medium', topic: 'Dunder methods', question: 'What does implementing __len__ and __getitem__ on a class enable?', options: ['Only len() support', 'len() support via __len__ and indexing/iteration support via __getitem__ — together they make the class a sequence that works with for loops, slicing, and built-in functions', 'Only dictionary-like access', 'Nothing useful outside of the class itself'], correct: 1, explanation: 'Implementing __getitem__(self, index) makes instances support obj[i] and iteration. Adding __len__ makes len(obj) work. Python\'s for loop uses __iter__ or falls back to __getitem__ starting at 0. This is the sequence protocol.' },
    { id: 'py-10', difficulty: 'Hard', topic: 'Metaclasses', question: 'What is a metaclass in Python?', options: ['A parent class that all classes inherit from', 'The class of a class — it controls how classes are created. type is the default metaclass. Custom metaclasses override __new__ or __init__ to modify class creation (e.g., ORMs, API frameworks)', 'A mixin that adds metadata to instances', 'A decorator that modifies class attributes'], correct: 1, explanation: 'In Python, classes are objects of type. A metaclass is the class whose instances are classes. By setting metaclass=MyMeta, you control class creation at definition time. Django\'s Model and SQLAlchemy use metaclasses to introspect field definitions and build ORM mappings.' },
  ],

  nodejs: [
    { id: 'node-1', difficulty: 'Easy', topic: 'Event loop', question: 'Node.js is single-threaded but can handle thousands of concurrent connections. How?', options: ['It secretly creates threads internally for each connection', 'The event loop and non-blocking I/O: I/O operations are offloaded to the OS/libuv thread pool. The single JS thread processes callbacks when I/O completes — no thread is blocked waiting', 'Node.js uses WebAssembly threads', 'V8 compiles JavaScript to multi-threaded native code'], correct: 1, explanation: 'Node.js uses libuv for async I/O. File/network I/O is handled by the OS asynchronously (epoll/kqueue/IOCP) or libuv\'s thread pool. The main thread handles the event loop, processing callbacks when operations complete — never blocking on I/O.' },
    { id: 'node-2', difficulty: 'Medium', topic: 'Streams', question: 'Why should you prefer streams over reading an entire file into memory with fs.readFile?', options: ['Streams are always faster', 'Streams process data in chunks — a 10GB file can be piped with constant memory. fs.readFile loads the entire file into RAM before processing', 'fs.readFile is deprecated', 'Streams have better error handling'], correct: 1, explanation: 'fs.readFile buffers the entire file in memory. Streaming reads in chunks (default 64KB) and processes each chunk before reading the next. For large files or HTTP responses, streaming allows piping data through (fs.createReadStream().pipe(res)) with O(1) memory.' },
    { id: 'node-3', difficulty: 'Hard', topic: 'Event loop phases', question: 'What is the order of Node.js event loop phases?', options: ['timers → I/O → idle/prepare → poll → check → close', 'poll → timers → I/O → check → close', 'I/O → timers → poll → check → close', 'All phases execute simultaneously'], correct: 0, explanation: 'The Node.js event loop phases in order: timers (setTimeout/setInterval callbacks) → pending I/O callbacks → idle/prepare (internal) → poll (retrieve new I/O events) → check (setImmediate) → close callbacks. Between phases, microtasks (process.nextTick, Promises) drain completely.' },
    { id: 'node-4', difficulty: 'Medium', topic: 'Cluster', question: 'Node.js runs on a single thread. How do you utilise all CPU cores?', options: ['Node.js automatically uses all cores', 'Use the cluster module or worker_threads: cluster forks multiple Node.js processes each with their own event loop; worker_threads share memory via SharedArrayBuffer', 'Install a multi-threading npm package', 'Configure V8 to use multiple cores'], correct: 1, explanation: 'cluster forks N worker processes (typically one per CPU core) that all share the same port — the OS load-balances connections between them. worker_threads run JS in parallel threads in the same process, sharing memory. PM2 simplifies cluster management in production.' },
    { id: 'node-5', difficulty: 'Easy', topic: 'Module system', question: 'What is the difference between CommonJS (require) and ES Modules (import)?', options: ['They are identical — just different syntax', 'CommonJS: synchronous loading, dynamic require() at any point, module.exports. ESM: static analysis (imports are hoisted, tree-shakeable), async loading, top-level await, .mjs or "type":"module" in package.json', 'ESM only works in browsers; CommonJS only in Node.js', 'require is deprecated in Node.js 18+'], correct: 1, explanation: 'CommonJS modules are evaluated synchronously and can be required dynamically. ESM imports are static — evaluated at parse time, making tree-shaking possible. ESM supports top-level await and is the standard. Node.js supports both but they don\'t interoperate without care.' },
    { id: 'node-6', difficulty: 'Hard', topic: 'Event loop', question: 'What is the difference between process.nextTick and setImmediate?', options: ['They are equivalent — both defer execution to the next iteration', 'process.nextTick fires before the next event loop phase (after current operation, before I/O). setImmediate fires in the check phase — after I/O callbacks in the same iteration', 'setImmediate is faster than process.nextTick', 'process.nextTick only works in older Node.js versions'], correct: 1, explanation: 'process.nextTick callbacks drain completely before the event loop advances to the next phase — they\'re microtasks. setImmediate runs in the check phase, after I/O callbacks. Nesting process.nextTick recursively can starve the event loop; setImmediate does not.' },
    { id: 'node-7', difficulty: 'Medium', topic: 'Error handling', question: 'What happens if an unhandled exception is thrown in a Node.js process?', options: ['The error is silently ignored', 'By default the process crashes. You can catch with process.on("uncaughtException") but it\'s risky — the process is in an undefined state', 'Node.js restarts the process automatically', 'The error is caught by the last Express middleware'], correct: 1, explanation: 'Unhandled exceptions crash the Node.js process. process.on("uncaughtException") can catch them but the docs warn: after an uncaught exception, the process may be in an undefined state — you should log and exit gracefully rather than try to continue.' },
    { id: 'node-8', difficulty: 'Easy', topic: 'Streams', question: 'What does backpressure mean in Node.js streams?', options: ['A stream reading backwards', 'When a writable stream\'s internal buffer fills up, write() returns false. The readable source should pause until "drain" fires — otherwise data accumulates in memory. .pipe() handles this automatically', 'An error that prevents streams from opening', 'A performance issue with synchronous I/O'], correct: 1, explanation: 'If you produce data faster than it can be consumed (e.g., reading a fast disk and writing to a slow network), the write buffer grows unboundedly. Backpressure is the signal to slow down. stream.pipe() implements backpressure automatically; manual stream use requires checking the return value of write().' },
  ],

  sql: [
    { id: 'sql-1', difficulty: 'Easy', topic: 'JOINs', question: 'What is the difference between INNER JOIN and LEFT JOIN?', options: ['They are identical', 'INNER JOIN returns only rows with matching values in both tables. LEFT JOIN returns all rows from the left table plus matching rows from the right — unmatched right rows become NULL', 'LEFT JOIN is faster than INNER JOIN', 'INNER JOIN works on more than 2 tables; LEFT JOIN only on 2'], correct: 1, explanation: 'INNER JOIN discards rows with no match in either table. LEFT JOIN (LEFT OUTER JOIN) preserves all left table rows — if no match exists in the right table, right-table columns are NULL. Use LEFT JOIN when you need all records from the primary table regardless of matches.' },
    { id: 'sql-2', difficulty: 'Medium', topic: 'Indexes', question: 'When would adding an index HURT performance?', options: ['Indexes always improve performance', 'On write-heavy tables: every INSERT/UPDATE/DELETE must update all indexes. An index on a column with low cardinality (e.g., boolean) rarely helps reads either', 'Indexes hurt on large tables', 'Indexes hurt on primary key columns'], correct: 1, explanation: 'Indexes speed up reads but slow writes because the index must be maintained on every data modification. On write-heavy tables (e.g., log ingestion), too many indexes become a bottleneck. Also, indexes on low-cardinality columns (gender, status) may not help the query planner enough to justify the write overhead.' },
    { id: 'sql-3', difficulty: 'Medium', topic: 'Transactions', question: 'What does the ACID property "Isolation" mean, and what anomalies does it prevent?', options: ['Isolation means tables cannot be accessed by multiple users simultaneously', 'Isolation controls how/when changes made by one transaction are visible to others. Higher isolation levels prevent: dirty reads, non-repeatable reads, and phantom reads — at the cost of concurrency', 'Isolation ensures data is backed up across multiple servers', 'Isolation means committed data survives system failures'], correct: 1, explanation: 'Isolation levels: READ UNCOMMITTED (dirty reads possible) → READ COMMITTED (prevents dirty reads) → REPEATABLE READ (prevents non-repeatable reads) → SERIALIZABLE (prevents phantom reads, fully isolated). Higher isolation = fewer anomalies but more locking and reduced throughput.' },
    { id: 'sql-4', difficulty: 'Hard', topic: 'Window functions', question: 'What does ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) give you?', options: ['The total count of rows per department', 'A sequential number for each row within each department, ordered by salary descending — resets to 1 for each new department', 'The rank of each employee by salary across the whole table', 'The running total of salaries per department'], correct: 1, explanation: 'ROW_NUMBER assigns a unique sequential integer to each row within a partition. PARTITION BY dept splits the numbering per department. ORDER BY salary DESC means rank 1 = highest salary in that dept. Unlike RANK(), ROW_NUMBER() never ties — two equal salaries still get different numbers.' },
    { id: 'sql-5', difficulty: 'Easy', topic: 'Indexes', question: 'What is a composite index and when should you use it?', options: ['An index on a computed/virtual column', 'An index on multiple columns. Most useful when your WHERE clause filters on multiple columns together — the index covers the full filter. Column order matters: the leftmost column must be in the filter to use the index', 'Two separate indexes on the same table', 'An index that stores compressed data'], correct: 1, explanation: 'A composite index (a, b, c) can serve queries filtering on a, a+b, or a+b+c — but not b alone or c alone (leftmost prefix rule). Design composite indexes to match your most common query patterns, with the highest-selectivity or equality-filtered column first.' },
    { id: 'sql-6', difficulty: 'Medium', topic: 'Query optimization', question: 'What is a query execution plan and how do you use it?', options: ['A scheduled query that runs on a timer', 'The database\'s plan for executing a query — shows whether indexes are used, join methods, estimated row counts. EXPLAIN (Postgres) / EXPLAIN PLAN (Oracle) reveals slow scans and missing indexes', 'A cached version of a frequently run query', 'A stored procedure that optimises queries automatically'], correct: 1, explanation: 'EXPLAIN ANALYZE (PostgreSQL) shows the actual execution plan with real row counts and timings. Look for: Seq Scan on large tables (missing index?), high estimated vs actual row count discrepancy (stale statistics?), or nested loop joins on large tables (hash join might be better).' },
    { id: 'sql-7', difficulty: 'Hard', topic: 'Transactions', question: 'What is a deadlock and how do databases resolve it?', options: ['A query that never finishes due to infinite loops', 'Two transactions each hold a lock the other needs, and both wait indefinitely. Databases detect the cycle and automatically abort one transaction (the "victim"), which is retried by the application', 'A locked table that requires a DBA to unlock manually', 'A deadlock occurs when a query exceeds the timeout'], correct: 1, explanation: 'Deadlock: Transaction A locks row 1, wants row 2. Transaction B locks row 2, wants row 1. Both wait forever. The database detects the dependency cycle (using a wait-for graph) and kills the transaction with the least cost to roll back, returning an error. Applications must retry on deadlock.' },
    { id: 'sql-8', difficulty: 'Medium', topic: 'Performance', question: 'What is the N+1 query problem in ORM usage?', options: ['Querying N tables with 1 query', 'Executing 1 query to get N records, then 1 additional query per record for related data — N+1 queries total instead of a single JOIN. Solved with eager loading (include/joinedload)', 'A performance issue caused by having more than N indexes', 'The problem of running the same query N times in a loop'], correct: 1, explanation: 'N+1 occurs when fetching a list (1 query) and then lazily loading a relationship for each item (N queries). For 100 users with posts, that\'s 101 queries instead of 1 JOIN. Fix: use eager loading (User.objects.select_related("posts") in Django, .include(:posts) in Rails).' },
  ],

  docker: [
    { id: 'docker-1', difficulty: 'Easy', topic: 'Basics', question: 'What is the difference between a Docker image and a container?', options: ['They are the same thing', 'An image is a read-only template (filesystem + metadata). A container is a running instance of an image — an image can spawn many containers', 'An image runs on the host; a container runs in the cloud', 'Containers are images with networking enabled'], correct: 1, explanation: 'An image is the blueprint (immutable, layered filesystem). A container is a running instance created from the image — it adds a writable layer on top. The same image can run as many containers simultaneously with isolated processes and filesystems.' },
    { id: 'docker-2', difficulty: 'Medium', topic: 'Dockerfile', question: 'Why should you order Dockerfile instructions from least-to-most frequently changing?', options: ['Docker requires alphabetical ordering', 'Docker caches layers. Changing a layer invalidates all subsequent layers. Put rarely-changing steps (system deps, npm install) before frequently-changing ones (COPY source code) to maximise cache hits and speed up builds', 'Docker builds faster with more layers at the top', 'Ordering doesn\'t matter — Docker rebuilds everything anyway'], correct: 1, explanation: 'Each Dockerfile instruction creates a cached layer. If a layer\'s input changes, that layer and all subsequent layers are rebuilt. Best practice: COPY package.json → RUN npm install → COPY source code. Changing source code only invalidates the last COPY, not the expensive npm install layer.' },
    { id: 'docker-3', difficulty: 'Medium', topic: 'Multi-stage builds', question: 'What problem do multi-stage builds solve?', options: ['They allow running multiple services in one container', 'They let you compile/build in a full SDK image, then COPY only the artifact into a minimal runtime image — eliminating build tools, compilers, and dev dependencies from the final image, dramatically reducing its size', 'They allow parallel build steps', 'They cache layers across different Docker hosts'], correct: 1, explanation: 'A Go binary compiled in a 800MB golang image can be copied into a 5MB scratch or alpine image. The final image contains no Go compiler, just the binary. This reduces attack surface (fewer packages = fewer CVEs), image size (faster pulls), and startup time.' },
    { id: 'docker-4', difficulty: 'Easy', topic: 'Volumes', question: 'When should you use a Docker volume vs bind mount?', options: ['Volumes are for reading; bind mounts are for writing', 'Volumes: managed by Docker, portable, work in production and CI (no host path dependency). Bind mounts: map a host directory into the container, ideal for development (live code reload). Use volumes in production', 'Bind mounts are faster in all situations', 'Volumes only work on Linux; bind mounts work everywhere'], correct: 1, explanation: 'Volumes are stored in Docker\'s managed storage area (docker volume create), are portable, work in Kubernetes, and don\'t have host path dependencies. Bind mounts (--volume /host/path:/container/path) are perfect for dev — changes on the host are immediately reflected in the container.' },
    { id: 'docker-5', difficulty: 'Hard', topic: 'Networking', question: 'How do containers on the same Docker network communicate?', options: ['They must use the host IP address', 'Containers on the same Docker bridge network can reach each other by container name (DNS resolution). Docker\'s embedded DNS resolves container names to their IP within the network', 'They must use port forwarding via the host', 'Containers cannot communicate directly — only via the host'], correct: 1, explanation: 'Docker creates an embedded DNS server. Containers on the same user-defined bridge network can resolve each other by container name or service name: `curl http://api:3000` from one container reaches the container named "api". The default bridge network does NOT have DNS — use user-defined networks.' },
    { id: 'docker-6', difficulty: 'Medium', topic: 'Dockerfile', question: 'Why run your application as a non-root user inside a container?', options: ['Root user is slower in containers', 'If the container is compromised, a root process could escape to the host or access host resources. A non-root user limits the blast radius of a container breakout', 'Docker requires non-root users', 'Root user cannot access the container filesystem'], correct: 1, explanation: 'Container processes run as root by default. If an attacker exploits a vulnerability, they have root-level access inside the container and may be able to escape to the host via kernel vulnerabilities. Best practice: create a dedicated user in the Dockerfile (RUN adduser app && USER app).' },
    { id: 'docker-7', difficulty: 'Hard', topic: 'Layers', question: 'What is the difference between CMD and ENTRYPOINT in a Dockerfile?', options: ['They are identical — both define the default command', 'ENTRYPOINT defines the executable that always runs; CMD provides default arguments to ENTRYPOINT (or the default command if no ENTRYPOINT). CMD is easily overridden with docker run args; ENTRYPOINT is not (unless --entrypoint is used)', 'CMD runs at build time; ENTRYPOINT runs at runtime', 'ENTRYPOINT is for shell scripts; CMD is for binary executables'], correct: 1, explanation: 'ENTRYPOINT sets the fixed executable: ENTRYPOINT ["nginx"]. CMD provides default flags: CMD ["-g", "daemon off;"]. Together: docker run myimage starts nginx with those flags. docker run myimage -c custom.conf overrides CMD args but keeps ENTRYPOINT. docker run --entrypoint bash myimage overrides ENTRYPOINT.' },
  ],

  kubernetes: [
    { id: 'k8s-1', difficulty: 'Easy', topic: 'Basics', question: 'What is the smallest deployable unit in Kubernetes?', options: ['A container', 'A Pod — one or more containers that share network namespace and storage, always scheduled together on the same node', 'A Deployment', 'A Node'], correct: 1, explanation: 'A Pod is the atomic unit. Containers in a Pod share localhost (same IP, ports), and can share volumes. You rarely create Pods directly — a Deployment or StatefulSet manages them. A Pod with one container is the most common pattern; sidecars (logging, proxies) use multi-container Pods.' },
    { id: 'k8s-2', difficulty: 'Medium', topic: 'Networking', question: 'What is the difference between a ClusterIP, NodePort, and LoadBalancer service?', options: ['They are identical except for price', 'ClusterIP: internal-only virtual IP. NodePort: exposes a port on every node\'s IP (external access, but manual). LoadBalancer: provisions a cloud load balancer with a public IP. ClusterIP is the default', 'NodePort is for Ingress only; LoadBalancer is for services', 'ClusterIP routes outside the cluster; NodePort routes inside'], correct: 1, explanation: 'ClusterIP is internal — only accessible within the cluster. NodePort opens a port (30000-32767) on every node, accessible from outside via NodeIP:NodePort. LoadBalancer creates an external cloud LB (AWS ELB, GCP LB) — the standard for production external traffic.' },
    { id: 'k8s-3', difficulty: 'Medium', topic: 'Workloads', question: 'When would you use a StatefulSet instead of a Deployment?', options: ['Always — StatefulSets are the improved version of Deployments', 'When pods need stable network identity, ordered deployment/scaling, and persistent storage — databases (MySQL, Cassandra), Kafka, ZooKeeper. Deployments are for stateless services', 'StatefulSets are only for batch jobs', 'When you need more than 3 replicas'], correct: 1, explanation: 'StatefulSets provide: stable pod names (pod-0, pod-1), stable DNS (pod-0.service.namespace), ordered deployment and rolling updates, and persistent volumes that survive pod restarts. Essential for stateful workloads like databases where each pod needs unique, durable storage.' },
    { id: 'k8s-4', difficulty: 'Hard', topic: 'HPA', question: 'How does the Horizontal Pod Autoscaler (HPA) decide to scale?', options: ['It scales randomly based on time of day', 'The metrics-server collects resource metrics (CPU, memory). HPA compares current utilisation to the target. It calculates desiredReplicas = ceil(currentReplicas × (currentMetric / targetMetric)) and adjusts', 'HPA only scales based on Prometheus custom metrics', 'HPA scales when a pod crashes'], correct: 1, explanation: 'HPA samples metrics from metrics-server (or custom metrics adapters) at a configurable interval. It applies the formula: desired replicas = ceil(current × current/target). Example: 3 pods at 90% CPU with target 50% → ceil(3 × 90/50) = 6 pods. Scale-down has a cooldown to prevent flapping.' },
    { id: 'k8s-5', difficulty: 'Medium', topic: 'Security', question: 'What is RBAC in Kubernetes?', options: ['A network policy for restricting egress traffic', 'Role-Based Access Control: controls who (ServiceAccount, user, group) can perform which actions (verbs: get, list, create, delete) on which resources (pods, secrets, deployments) in which namespaces', 'A pod security policy for restricting container capabilities', 'An authentication mechanism replacing API keys'], correct: 1, explanation: 'Kubernetes RBAC has: Role (permissions in a namespace) or ClusterRole (cluster-wide). RoleBinding/ClusterRoleBinding grants the role to a subject. Fine-grained control: a ServiceAccount for your app can get/list pods but not delete them, and cannot access secrets in other namespaces.' },
    { id: 'k8s-6', difficulty: 'Easy', topic: 'Resources', question: 'What is the difference between resource requests and limits in Kubernetes?', options: ['They are the same — set both to the same value', 'Requests: the minimum guaranteed resources the scheduler uses for placement. Limits: the maximum the container can use. Going over CPU limit throttles; going over memory limit kills the pod (OOMKilled)', 'Requests are for CPU; limits are for memory only', 'Limits are enforced at the node level; requests are enforced at the pod level'], correct: 1, explanation: 'The scheduler uses requests to find a node with enough capacity. Limits cap usage — CPU is throttled (reduced, not killed) if exceeded; memory is not compressible, so exceeding the limit causes an OOMKill. Set requests close to typical usage and limits slightly above to handle bursts.' },
    { id: 'k8s-7', difficulty: 'Hard', topic: 'Scheduling', question: 'How do taints and tolerations work in Kubernetes?', options: ['Taints label nodes; tolerations label pods — they serve the same purpose', 'Taints on nodes repel pods. Tolerations on pods allow them to be scheduled onto tainted nodes. Used to dedicate nodes for specific workloads (GPU nodes, spot instances) while keeping regular pods off them', 'Taints are affinity rules; tolerations are anti-affinity rules', 'They are deprecated in favor of node selectors'], correct: 1, explanation: 'kubectl taint node gpu-node gpu=true:NoSchedule marks a node so no pod can run there unless the pod has a matching toleration. GPU workloads add tolerations to run on the GPU node; regular pods without the toleration cannot be scheduled there. NoSchedule, PreferNoSchedule, and NoExecute are the effects.' },
  ],

  git: [
    { id: 'git-1', difficulty: 'Easy', topic: 'Branching', question: 'What is the difference between git merge and git rebase?', options: ['They are identical', 'Merge creates a merge commit preserving history as it happened. Rebase replays commits on top of another branch, creating a linear history. Rebase rewrites commit SHAs — never rebase shared/public branches', 'Rebase deletes the source branch; merge does not', 'Merge is for feature branches; rebase is for hotfixes only'], correct: 1, explanation: 'git merge main: creates a merge commit, preserves exact history (good for auditing). git rebase main: replays your commits on top of main — cleaner history but rewrites SHAs. The golden rule: never rebase commits that others have already pulled.' },
    { id: 'git-2', difficulty: 'Medium', topic: 'Internals', question: 'What are the four core Git object types?', options: ['commit, branch, tag, stash', 'blob (file contents), tree (directory), commit (snapshot with metadata), tag (annotated pointer) — all content-addressed by SHA-1/SHA-256 hash', 'file, folder, commit, merge', 'push, pull, fetch, clone'], correct: 1, explanation: 'Git is a content-addressable filesystem. Every object is stored by the hash of its content. blob stores file content. tree stores a directory (lists blobs and sub-trees). commit stores a tree + parent commits + author/message. Annotated tag stores a commit reference with a message.' },
    { id: 'git-3', difficulty: 'Medium', topic: 'Reflog', question: 'What is git reflog used for?', options: ['Viewing the diff between two branches', 'The reflog records every time HEAD moves — commits, resets, rebases. If you lose commits with git reset --hard or a bad rebase, reflog lets you find and recover them', 'Listing all remote branches', 'Checking file history for a specific path'], correct: 1, explanation: 'git reflog shows the history of HEAD movements with timestamps. After a destructive operation (reset --hard, rebase), you can find the lost commit SHA in the reflog and restore it: git checkout -b recovery <sha>. Reflog entries expire after 90 days by default.' },
    { id: 'git-4', difficulty: 'Easy', topic: 'Basics', question: 'What is the difference between git fetch and git pull?', options: ['They are identical', 'git fetch downloads remote changes into tracking branches without modifying your working tree. git pull = git fetch + git merge (or rebase) — it downloads AND integrates changes', 'git fetch only works on the main branch', 'git pull is safer than git fetch'], correct: 1, explanation: 'git fetch is safe — it updates remote-tracking branches (origin/main) but leaves your local branches untouched. git pull fetches then immediately merges or rebases, modifying your working branch. Use fetch + review before merging to avoid surprises.' },
    { id: 'git-5', difficulty: 'Hard', topic: 'Interactive rebase', question: 'What operations does git rebase -i allow?', options: ['Only squashing commits', 'Reorder commits, edit commit messages (reword), squash/fixup commits (combine), split commits, drop commits, and exec shell commands between commits', 'Only rebasing onto a different branch', 'Interactive rebase only works on the last 2 commits'], correct: 1, explanation: 'Interactive rebase opens a text editor listing commits with pick/reword/edit/squash/fixup/drop commands. squash combines a commit with the previous one (keeping both messages); fixup is the same but discards the squashed message. Ideal for cleaning up a messy feature branch before merging.' },
    { id: 'git-6', difficulty: 'Medium', topic: 'Cherry-pick', question: 'When would you use git cherry-pick?', options: ['To undo the last commit', 'To apply a specific commit from one branch onto another without merging the entire branch — useful for backporting a bug fix to a release branch without pulling in all feature commits', 'To delete commits from history', 'To merge two branches interactively'], correct: 1, explanation: 'git cherry-pick <sha> copies the changes from one specific commit onto your current branch as a new commit. Common use: a bug fix is committed on main and you need to apply it to the v2.1-stable release branch without bringing in unrelated feature commits.' },
    { id: 'git-7', difficulty: 'Hard', topic: 'Internals', question: 'What does git reset --soft, --mixed, and --hard each do?', options: ['They all do the same thing', 'All three move HEAD (and current branch) to the target commit. --soft leaves the index and working tree unchanged. --mixed (default) resets the index but leaves the working tree. --hard resets both index and working tree — destructive, data loss possible', '--soft is safest; --hard is used only for remote branches', '--mixed and --hard are deprecated in favor of git restore'], correct: 1, explanation: 'Think of it as "how much do you throw away?": --soft: keep staged and unstaged changes (just move HEAD — good for undoing a commit while keeping changes staged). --mixed: unstage changes, keep files (default). --hard: discard all changes — files revert to the target commit state. --hard can lose work permanently.' },
  ],

  go: [
    { id: 'go-1', difficulty: 'Easy', topic: 'Goroutines', question: 'What is a goroutine and how does it differ from an OS thread?', options: ['Goroutines are the same as OS threads', 'Goroutines are user-space coroutines managed by the Go runtime. They are much lighter (2KB initial stack vs 1-2MB for threads), multiplexed onto OS threads by the runtime scheduler (M:N threading)', 'Goroutines always run on a single CPU core', 'Goroutines cannot share memory with other goroutines'], correct: 1, explanation: 'The Go runtime multiplexes thousands of goroutines onto a small pool of OS threads. Goroutine stacks grow and shrink dynamically (starting at 2KB). The runtime scheduler moves goroutines between threads transparently. You can run a million goroutines with modest memory.' },
    { id: 'go-2', difficulty: 'Medium', topic: 'Channels', question: 'What is the difference between a buffered and unbuffered channel?', options: ['Buffered channels are always faster', 'Unbuffered: sender blocks until receiver is ready (synchronous rendezvous). Buffered ch := make(chan T, N): sender can proceed without a receiver until the buffer is full; receiver blocks only when empty', 'Buffered channels can only hold one value', 'Unbuffered channels are deprecated in Go 1.18+'], correct: 1, explanation: 'make(chan int) is unbuffered — send and receive must synchronise, creating a handshake. make(chan int, 100) buffers 100 values — the sender is only blocked when the buffer is full. Unbuffered channels are useful for explicit synchronisation; buffered for decoupling producer/consumer rates.' },
    { id: 'go-3', difficulty: 'Medium', topic: 'Interfaces', question: 'How does Go implement interfaces differently from Java or C#?', options: ['Go uses explicit "implements" keyword', 'Go uses structural typing (duck typing) — a type automatically satisfies an interface if it implements all the interface\'s methods, with no explicit declaration', 'Go interfaces require inheritance', 'Go does not have interfaces — it uses generics instead'], correct: 1, explanation: 'In Go, you never write "implements io.Reader". If your type has a Read(p []byte) (n int, err error) method, it automatically satisfies io.Reader. This enables loose coupling: code written against an interface works with any type that happens to implement the methods, even types in other packages.' },
    { id: 'go-4', difficulty: 'Hard', topic: 'Garbage collector', question: 'What type of garbage collector does Go use and what is its goal?', options: ['Reference counting like Python', 'A concurrent tri-color mark-and-sweep GC. Its primary goal is minimising stop-the-world pauses (target < 1ms), not maximum throughput', 'A generational GC like Java\'s HotSpot', 'Go has no GC — developers manage memory manually'], correct: 1, explanation: 'Go\'s GC runs concurrently with the application (most work done while Go code runs). It uses a tri-color marking algorithm. The design prioritises low latency over throughput — acceptable for network servers. You can tune it with GOGC (default: 100 = collect when heap doubles).' },
    { id: 'go-5', difficulty: 'Easy', topic: 'Error handling', question: 'How does Go handle errors compared to try/catch in other languages?', options: ['Go uses panic/recover for all errors', 'Go treats errors as values — functions return (result, error). The caller explicitly checks and handles the error. panic/recover is for truly exceptional situations, not normal error flow', 'Go uses exceptions with defer/panic', 'Go ignores errors by default'], correct: 1, explanation: 'In Go, error handling is explicit: if err != nil { return fmt.Errorf("context: %w", err) }. This makes error paths visible in code. panic is reserved for unrecoverable situations (index out of bounds, nil pointer). recover() can catch panics in deferred functions.' },
    { id: 'go-6', difficulty: 'Medium', topic: 'Concurrency', question: 'What does "Do not communicate by sharing memory; share memory by communicating" mean in Go?', options: ['Go does not support shared memory', 'Prefer channels to coordinate between goroutines over mutexes + shared variables. Channels pass ownership of data, reducing the need for locks and making data flow explicit', 'Go memory is always shared between goroutines', 'It means all Go programs must be single-threaded'], correct: 1, explanation: 'The Go proverb encourages using channels (passing values) over mutexes (shared memory). Instead of goroutine A and B both accessing a shared slice with a mutex, goroutine A sends data through a channel to B — only one goroutine owns the data at a time, eliminating race conditions by design.' },
    { id: 'go-7', difficulty: 'Hard', topic: 'Interfaces', question: 'What is the difference between a nil interface and an interface holding a nil pointer?', options: ['They are identical', 'A nil interface has no type information and no value — comparing it to nil returns true. An interface holding a nil pointer has concrete type information with a nil pointer value — it is NOT nil even though the pointer inside is nil', 'Neither can be compared to nil', 'A nil pointer interface panics on comparison'], correct: 1, explanation: 'var err error = nil — nil interface (type=nil, value=nil). var p *MyError = nil; var err error = p — non-nil interface (type=*MyError, value=nil). The interface itself is not nil because it has a type. This surprises many Go developers: if err != nil is true even though the concrete value is a nil pointer.' },
  ],

  aws: [
    { id: 'aws-1', difficulty: 'Easy', topic: 'EC2', question: 'What is the difference between an EC2 on-demand instance and a reserved instance?', options: ['They are identical hardware', 'On-demand: pay by the hour with no commitment. Reserved: 1 or 3-year commitment for up to 72% discount. Use reserved for predictable baseline load, on-demand for bursts', 'Reserved instances are always faster', 'On-demand instances cannot be stopped'], correct: 1, explanation: 'On-demand pricing is flexible but expensive for steady-state workloads. Reserved Instances commit to 1 or 3 years in exchange for steep discounts. Savings Plans offer similar discounts with more flexibility. Spot Instances (up to 90% cheaper) can be interrupted — ideal for batch/stateless workloads.' },
    { id: 'aws-2', difficulty: 'Medium', topic: 'VPC', question: 'What is the purpose of a VPC (Virtual Private Cloud) and its subnets?', options: ['VPC is a CDN for EC2 instances', 'VPC is an isolated virtual network in AWS. Subnets divide it into segments: public subnets have internet access (via Internet Gateway); private subnets are internal only (accessed via NAT Gateway for outbound)', 'VPC is only used for database instances', 'VPC is identical to a traditional VLAN'], correct: 1, explanation: 'A VPC gives you a private network within AWS. You control CIDR ranges, route tables, and security. Public subnets route through an Internet Gateway (can have public IPs). Private subnets route outbound through a NAT Gateway but have no inbound access from the internet — where you run databases and internal services.' },
    { id: 'aws-3', difficulty: 'Medium', topic: 'IAM', question: 'What is the principle of least privilege in AWS IAM?', options: ['All users should have admin access for convenience', 'Grant only the minimum permissions needed to perform a task. A Lambda function that reads from S3 should only have s3:GetObject on that specific bucket — not s3:* on all buckets', 'IAM roles always have full access by default', 'Least privilege means read-only access for everyone'], correct: 1, explanation: 'Least privilege limits the blast radius of a compromised credential. Use IAM roles (not access keys) for EC2/Lambda, scope permissions to specific resources with ARNs, and use conditions (source IP, MFA required) to further restrict. Regular audits with IAM Access Analyzer identify overly permissive policies.' },
    { id: 'aws-4', difficulty: 'Easy', topic: 'S3', question: 'What is the difference between S3 Standard, S3 Infrequent Access, and S3 Glacier?', options: ['They are the same storage with different marketing names', 'Standard: frequent access, highest cost. Infrequent Access: lower storage cost + per-retrieval fee — for data accessed monthly. Glacier: very low storage cost + high retrieval latency/cost — for archival (minutes to hours to retrieve)', 'Glacier is only for compliance data', 'Infrequent Access is slower because data is stored on tape'], correct: 1, explanation: 'S3 tiers trade cost for access speed/frequency. Standard: $0.023/GB/month, instant access. S3-IA: $0.0125/GB/month + $0.01/GB retrieval — for backups accessed rarely. Glacier Instant: immediate retrieval. Glacier Flexible: 1-12 hours. Deep Archive: 12-48 hours, cheapest ($0.00099/GB). Lifecycle policies automatically move objects between tiers.' },
    { id: 'aws-5', difficulty: 'Hard', topic: 'Lambda', question: 'What is a Lambda cold start and how do you mitigate it?', options: ['Lambda always has the same latency', 'A cold start occurs when Lambda needs to initialise a new execution environment (download code, start runtime, run init code) before handling a request — adds 100ms-5s latency. Mitigations: provisioned concurrency, small deployment packages, keep-warm pings, or using runtimes with faster starts (Go, Rust)', 'Cold starts only happen once per day', 'Cold starts only affect Java and .NET'], correct: 1, explanation: 'When Lambda receives a request and no warm execution environment exists, it provisions one (cold start). Subsequent requests reuse the warm environment. Provisioned Concurrency keeps environments pre-warmed (costs money). Minimise package size, move expensive init outside the handler, and prefer compiled runtimes for latency-sensitive functions.' },
    { id: 'aws-6', difficulty: 'Medium', topic: 'High availability', question: 'Why should you deploy resources across multiple Availability Zones?', options: ['To reduce AWS costs', 'Each AZ is an independent datacenter with its own power and networking. An AZ failure (fire, power outage) only affects that AZ. Multi-AZ deployment survives an AZ outage without service interruption', 'To improve read performance with geographic caching', 'AWS requires multi-AZ for all production workloads'], correct: 1, explanation: 'An AZ is isolated infrastructure — failures in one don\'t cascade to others. For high availability, distribute EC2 instances across ≥2 AZs behind an ALB, use Multi-AZ RDS for automatic failover, and use S3 (which is inherently multi-AZ). The goal: survive a single AZ failure with zero downtime.' },
    { id: 'aws-7', difficulty: 'Hard', topic: 'Networking', question: 'What is the difference between a Security Group and a Network ACL in AWS?', options: ['They are identical', 'Security Groups: stateful, apply at the instance level, allow rules only. NACLs: stateless, apply at the subnet level, allow and deny rules. Stateful means return traffic is automatically allowed in SGs; NACLs require explicit inbound and outbound rules for each direction', 'NACLs only apply to RDS; Security Groups to EC2', 'Security Groups are applied after NACLs in the request path'], correct: 1, explanation: 'Security Groups are stateful — if you allow port 443 inbound, the response traffic is automatically allowed outbound. NACLs are stateless — you must explicitly allow both inbound port 443 AND outbound ephemeral ports (1024-65535) for the response. NACLs are evaluated before reaching the instance (subnet level); SGs are the last defense (instance level).' },
  ],

  linux: [
    { id: 'linux-1', difficulty: 'Easy', topic: 'Permissions', question: 'What does the permission string -rwxr-xr-- represent?', options: ['A directory with full access', 'A regular file: owner has read/write/execute (rwx), group has read/execute (r-x), others have read-only (r--)', 'A symbolic link with no permissions', 'A file where only the owner can read'], correct: 1, explanation: 'The first character (-=file, d=directory, l=symlink). Then 3 groups of rwx for owner, group, others. rwx=7, r-x=5, r--=4 in octal notation. chmod 754 sets this: owner full, group r+x, others read-only.' },
    { id: 'linux-2', difficulty: 'Medium', topic: 'Process management', question: 'What is the difference between a process and a thread in Linux?', options: ['They are identical', 'A process has its own isolated memory space. Threads (lightweight processes) within the same process share memory/file descriptors. Linux uses clone() for both — the difference is which resources are shared', 'Threads run faster than processes always', 'Processes cannot communicate; threads can'], correct: 1, explanation: 'In Linux, both processes and threads are created with clone() with different flags. CLONE_VM (share memory) creates a thread; without it, the child gets a copy-on-write copy of the parent\'s memory (fork). Context switching between threads is cheaper because no TLB flush is needed (same address space).' },
    { id: 'linux-3', difficulty: 'Medium', topic: 'Shell scripting', question: 'What does set -e do at the top of a bash script?', options: ['It encrypts the script', 'It makes the script exit immediately if any command returns a non-zero exit code — preventing silent failures from propagating', 'It runs the script in debug mode', 'It enables strict variable declaration'], correct: 1, explanation: 'Without set -e, a failing command in a script is ignored and execution continues. set -e (errexit) makes the script abort on first error. Combine with set -u (exit on undefined variable) and set -o pipefail (pipelines fail if any command fails) for robust scripts.' },
    { id: 'linux-4', difficulty: 'Easy', topic: 'Networking', question: 'What does netstat -tlnp or ss -tlnp show?', options: ['Packet loss statistics', 'All TCP listening sockets with their port and the PID of the process holding them — useful for finding which process is bound to a port', 'All established connections only', 'Network interface statistics'], correct: 1, explanation: 'ss (socket statistics, modern replacement for netstat) with -t (TCP), -l (listening), -n (numeric), -p (process) shows every port currently being listened on and which PID/process owns it. Useful for: "what is using port 8080?" or "is my service actually listening?"' },
    { id: 'linux-5', difficulty: 'Hard', topic: 'Systemd', question: 'What is the difference between ExecStart and ExecStartPre in a systemd service unit?', options: ['They are identical', 'ExecStartPre runs before ExecStart — for setup tasks (e.g., creating directories, checking prerequisites). If ExecStartPre fails, the service is considered failed and ExecStart does not run', 'ExecStart is for one-shot tasks; ExecStartPre is for persistent services', 'ExecStartPre runs as root; ExecStart runs as the service user'], correct: 1, explanation: 'systemd executes ExecStartPre commands in order before starting the main process (ExecStart). Multiple ExecStartPre lines are allowed. If any fails (returns non-zero), the service fails to start. Use for: config validation, database migrations, directory creation, environment checks.' },
    { id: 'linux-6', difficulty: 'Medium', topic: 'File system', question: 'What is an inode in Linux?', options: ['A type of network interface', 'A data structure storing file metadata (permissions, owner, timestamps, block pointers) — everything except the filename. The directory maps filename → inode number', 'The first block of data in a file', 'A kernel process for I/O'], correct: 1, explanation: 'An inode stores: file type, permissions, owner/group, size, timestamps, and pointers to data blocks. Directories are files that map names to inode numbers. Hard links are two directory entries pointing to the same inode. Soft links (symlinks) point to a pathname. "No space left on device" can mean full inodes even with free disk space.' },
    { id: 'linux-7', difficulty: 'Hard', topic: 'Performance', question: 'What does /proc/sys/net/core/somaxconn control?', options: ['Maximum number of network interfaces', 'The maximum length of the accept queue for new TCP connections — if this fills up, new connection attempts are dropped. Must be increased for high-concurrency servers', 'Maximum socket buffer size', 'The number of file descriptors per process'], correct: 1, explanation: 'somaxconn is the kernel\'s maximum backlog queue length for TCP accept(). When a server\'s accept() loop can\'t keep up, new SYN packets queue here. If the queue fills, new connections are refused. High-traffic servers set this to 65535 (also tune net.ipv4.tcp_max_syn_backlog and SO_BACKLOG in the application).' },
  ],
}
