export interface Problem {
  id: string
  title: string
  subtitle: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  duration: string
  companies: string[]
  description: string
  tags: string[]
}

export const PROBLEMS: Problem[] = [
  {
    id: 'url-shortener',
    title: 'URL Shortener',
    subtitle: 'Design bit.ly',
    difficulty: 'Easy',
    duration: '30 min',
    companies: ['Google', 'Amazon'],
    description: '100M URLs, custom aliases, sub-10ms redirects',
    tags: ['storage', 'hashing', 'caching', 'redirect'],
  },
  {
    id: 'instagram',
    title: 'Instagram',
    subtitle: 'Photo sharing feed',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Meta', 'Instagram'],
    description: '500M DAU, photo uploads, personalized feeds',
    tags: ['feed', 'object-storage', 'cdn', 'social'],
  },
  {
    id: 'youtube',
    title: 'YouTube',
    subtitle: 'Video platform',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Google'],
    description: 'Video upload pipeline, CDN delivery, transcoding',
    tags: ['video', 'cdn', 'transcoding', 'object-storage'],
  },
  {
    id: 'uber',
    title: 'Uber',
    subtitle: 'Ride sharing',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Uber', 'Lyft'],
    description: 'Real-time matching, GPS tracking, surge pricing',
    tags: ['geospatial', 'real-time', 'matching', 'websocket'],
  },
  {
    id: 'whatsapp',
    title: 'WhatsApp',
    subtitle: 'Messaging at scale',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Meta'],
    description: '100B messages/day, E2E encryption, offline delivery',
    tags: ['messaging', 'websocket', 'encryption', 'real-time'],
  },
  {
    id: 'twitter-feed',
    title: 'Twitter/X Feed',
    subtitle: 'Social news feed',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Meta', 'Twitter'],
    description: 'News feed, fan-out, 500M users, real-time timeline',
    tags: ['feed', 'fan-out', 'social', 'real-time', 'distributed'],
  },
  {
    id: 'google-drive',
    title: 'Google Drive',
    subtitle: 'Cloud file storage',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Google', 'Dropbox'],
    description: 'File storage, sync, sharing, version history',
    tags: ['storage', 'sync', 'distributed', 'versioning'],
  },
  {
    id: 'rate-limiter',
    title: 'Rate Limiter',
    subtitle: 'API traffic control',
    difficulty: 'Easy',
    duration: '30 min',
    companies: ['Any company'],
    description: 'Token bucket, sliding window, distributed enforcement',
    tags: ['distributed', 'caching', 'algorithms', 'api'],
  },
  {
    id: 'search-autocomplete',
    title: 'Search Autocomplete',
    subtitle: 'Typeahead suggestions',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Google', 'Amazon'],
    description: 'Typeahead suggestions, prefix trees, 100M QPS',
    tags: ['search', 'trie', 'caching', 'real-time'],
  },
  {
    id: 'notification-system',
    title: 'Notification System',
    subtitle: 'Push, email & SMS delivery',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Meta', 'Apple'],
    description: 'Push/email/SMS, fan-out, deduplication',
    tags: ['messaging', 'fan-out', 'queues', 'distributed'],
  },
  {
    id: 'payment-system',
    title: 'Payment System',
    subtitle: 'Payments at scale',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Stripe', 'PayPal'],
    description: 'ACID transactions, idempotency, fraud detection',
    tags: ['transactions', 'consistency', 'security', 'distributed'],
  },
  {
    id: 'slack',
    title: 'Slack / Discord',
    subtitle: 'Real-time team messaging',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Slack'],
    description: 'Real-time messaging, channels, search, 10M concurrent users',
    tags: ['messaging', 'websocket', 'real-time', 'search'],
  },
  {
    id: 'netflix',
    title: 'Netflix',
    subtitle: 'Streaming platform',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Netflix'],
    description: 'Content delivery, recommendation engine, global streaming',
    tags: ['video', 'cdn', 'recommendations', 'distributed'],
  },
  {
    id: 'tiktok-feed',
    title: 'TikTok Feed',
    subtitle: 'Short video recommendation',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['ByteDance', 'TikTok'],
    description: 'Short video feed, ML ranking, creator pipeline',
    tags: ['feed', 'ml', 'video', 'recommendations', 'real-time'],
  },
  {
    id: 'dropbox',
    title: 'Dropbox Sync',
    subtitle: 'File sync service',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Dropbox'],
    description: 'Delta sync, conflict resolution, chunked uploads',
    tags: ['storage', 'sync', 'distributed', 'chunking'],
  },
  {
    id: 'airbnb',
    title: 'Airbnb Booking',
    subtitle: 'Property booking platform',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Airbnb'],
    description: 'Search, availability calendar, double-booking prevention',
    tags: ['search', 'transactions', 'consistency', 'geospatial'],
  },
  {
    id: 'web-crawler',
    title: 'Web Crawler',
    subtitle: 'Distributed web indexer',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Google'],
    description: 'Distributed crawler, URL dedup, robots.txt, scale to billions',
    tags: ['distributed', 'queues', 'storage', 'deduplication'],
  },
  {
    id: 'live-streaming',
    title: 'Live Video Streaming',
    subtitle: 'Twitch / YouTube Live',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Twitch', 'YouTube Live'],
    description: 'Ingest pipeline, WebRTC, low-latency CDN',
    tags: ['video', 'cdn', 'real-time', 'websocket'],
  },
  {
    id: 'ride-sharing',
    title: 'Lyft Ride Sharing',
    subtitle: 'Ride matching platform',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Lyft'],
    description: 'Geospatial matching, ETA calculation, driver state machine',
    tags: ['geospatial', 'real-time', 'matching', 'state-machine'],
  },
  {
    id: 'news-feed',
    title: 'Facebook News Feed',
    subtitle: 'Social graph feed',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['Meta'],
    description: 'Social graph, ranking, fan-out, EdgeRank',
    tags: ['feed', 'fan-out', 'social', 'ml', 'graph'],
  },
  {
    id: 'typeahead-search',
    title: 'Typeahead Search',
    subtitle: 'Instant search suggestions',
    difficulty: 'Easy',
    duration: '30 min',
    companies: ['Google', 'Bing'],
    description: 'Trie, top-K suggestions, personalization',
    tags: ['search', 'trie', 'caching', 'algorithms'],
  },
  {
    id: 'distributed-cache',
    title: 'Distributed Cache',
    subtitle: 'Redis / Memcached at scale',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Redis', 'Memcached'],
    description: 'Consistent hashing, eviction policies, replication',
    tags: ['caching', 'distributed', 'consistent-hashing', 'replication'],
  },
  {
    id: 'hotel-booking',
    title: 'Hotel Booking',
    subtitle: 'Booking.com / Expedia',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Booking.com', 'Expedia'],
    description: 'Search, inventory management, overbooking prevention',
    tags: ['search', 'transactions', 'consistency', 'inventory'],
  },
  {
    id: 'stock-exchange',
    title: 'Stock Exchange',
    subtitle: 'NASDAQ / NYSE order matching',
    difficulty: 'Hard',
    duration: '60 min',
    companies: ['NASDAQ', 'NYSE'],
    description: 'Order matching, low-latency, ACID, market data feed',
    tags: ['transactions', 'low-latency', 'consistency', 'real-time'],
  },
  {
    id: 'email-service',
    title: 'Email Service',
    subtitle: 'Design Gmail',
    difficulty: 'Medium',
    duration: '45 min',
    companies: ['Gmail'],
    description: 'Delivery pipeline, spam filtering, search, attachments',
    tags: ['messaging', 'storage', 'search', 'queues'],
  },
]
