export type ScenarioType = 'scenario' | 'edge-case' | 'tradeoff' | 'gotcha'
export type ScenarioDifficulty = 'Easy' | 'Medium' | 'Hard'

export interface TopicScenario {
  q: string
  type: ScenarioType
  difficulty: ScenarioDifficulty
}

export const TOPIC_SCENARIOS: Record<string, TopicScenario[]> = {
  'load-balancing': [
    { q: 'Your load balancer is the single point of failure. A user says "just add redundancy" — walk me through exactly how you make it highly available.', type: 'scenario', difficulty: 'Medium' },
    { q: 'You use round-robin load balancing. One server is 4× faster than the others. How do you fix the uneven load distribution?', type: 'tradeoff', difficulty: 'Easy' },
    { q: 'A client has a session stored in-memory on Server A. The load balancer routes their next request to Server B. What breaks, and what are your options?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'You are load balancing HTTP/2 connections. Why does round-robin break at the connection level?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Explain consistent hashing. If you have 100 keys spread across 10 nodes and you add an 11th node, how many keys move?', type: 'scenario', difficulty: 'Medium' },
    { q: 'What is a "thundering herd" in the context of load balancing, and when does it happen?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Your health check endpoint returns 200 but the server is actually stuck processing a slow database query and dropping real requests. How do you catch this?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'L4 vs L7 load balancing — give me a real scenario where you would specifically need L7.', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'You have a load balancer in front of WebSocket connections. What breaks if the load balancer terminates each message separately?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Two data centers, each with a load balancer. A user in Europe gets routed to the US. How do you fix geo-routing?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Your load balancer uses least-connections algorithm. A server is slow but not down — its active connection count is low because connections just hang. What happens?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'SSL termination at the load balancer — what are the security implications of unencrypted traffic between the LB and backend servers?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'You have 10 servers. During a deploy, you take 2 down at a time. How does the load balancer know not to route traffic to servers being updated?', type: 'scenario', difficulty: 'Easy' },
    { q: 'Sticky sessions solve the session affinity problem. What new problem do they introduce at scale?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your load balancer is CPU-bound at 1M RPS. How do you scale the load balancer itself?', type: 'scenario', difficulty: 'Hard' },
    { q: 'A backend server starts returning 503s intermittently. How does a good load balancer respond differently from a naive one?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Virtual nodes in consistent hashing — why are they needed and what problem do they solve?', type: 'scenario', difficulty: 'Hard' },
    { q: 'The load balancer adds ~1ms latency per hop. Your SLA is 5ms end-to-end. Do you put a load balancer in the critical path?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A client retries a POST request after a timeout. The request already executed on the server. What role does idempotency play here?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'How would you implement a "blue-green" deployment using only load balancer configuration?', type: 'scenario', difficulty: 'Medium' },
    { q: 'DNS-based load balancing vs hardware/software LB — when would you use each?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your load balancer is sending traffic to a server that just started. The server\'s JVM hasn\'t warmed up. Users get high latency. How do you handle this?', type: 'edge-case', difficulty: 'Hard' },
  ],

  'caching': [
    { q: 'You add a cache in front of your database. Cache hit rate is 60%. Is that good or bad, and what determines the target?', type: 'scenario', difficulty: 'Easy' },
    { q: 'Cache stampede: your cache key expires and 50,000 users simultaneously try to regenerate it from the database. Walk me through the failure and three ways to fix it.', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Write-through vs write-behind caching — give me a real scenario where each is the better choice.', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'You cache user profile data with a 1-hour TTL. A user updates their email. Another user\'s request shows the old email for up to 1 hour. Is this acceptable, and how would you fix it if not?', type: 'scenario', difficulty: 'Medium' },
    { q: 'What is a "hot key" problem in Redis, and how do you solve it without removing the cache entirely?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Your Redis instance runs out of memory. The eviction policy is set to noeviction. What happens, and what would you set instead?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'You have a distributed cache across 10 nodes. You add an 11th node. What fraction of cache keys become invalid with simple modular hashing?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Cache-aside vs read-through — which one do YOU control, and what\'s the danger of inconsistency in cache-aside?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'You store a user\'s shopping cart in a Redis hash. The user adds 10,000 items (pathological case). What Redis data structure pitfall might appear?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Two microservices each have their own local cache of the same data. Service A updates the database. How long until Service B\'s cache is stale?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'Your cache is a read-through. The database is down. What does the cache return for keys that are already cached vs. keys that aren\'t?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'You use Redis for rate limiting. A Redis node fails and is replaced. What happens to all the rate limit counters?', type: 'scenario', difficulty: 'Hard' },
    { q: 'LRU vs LFU eviction — you have a news site where old articles are rarely read but occasionally spike. Which eviction policy is better?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'You cached a database query result. The underlying data changes in the database. Name three strategies for invalidating the cache entry.', type: 'scenario', difficulty: 'Easy' },
    { q: 'A cache entry has TTL=0 (infinite). What scenario causes this to break your system over time?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'Your cache hit rate dropped from 90% to 50% overnight. How would you diagnose this?', type: 'scenario', difficulty: 'Hard' },
    { q: 'You deploy a new version of your app that changes the serialization format of cached objects. What happens to existing cache entries?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Redis vs Memcached — give me one specific scenario where you\'d choose each.', type: 'tradeoff', difficulty: 'Easy' },
    { q: 'You have a multilayer cache (L1 local + L2 Redis). A write invalidates only the Redis entry. What\'s the stale window for the local cache?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Cache key collisions — two different objects hash to the same cache key. How would you detect this and what\'s the impact?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'You cache API responses from a third-party service. The third-party returns different data for different users (personalized). How does your caching strategy change?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Read-your-writes consistency: you update your profile and immediately refresh the page — but the cache shows your old data. How do you fix this while keeping cache efficiency?', type: 'edge-case', difficulty: 'Medium' },
  ],

  'queues': [
    { q: 'You have a Kafka topic with 10 partitions and 10 consumers in a group. You add an 11th consumer. What happens?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'Your queue consumer is processing messages but the queue depth keeps growing. What are the possible causes and how do you diagnose each?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Exactly-once semantics vs at-least-once — explain the tradeoff with a real payment processing example.', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A consumer crashes mid-processing of a message after writing to the database but before committing the offset. What happens when it restarts?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'You have a dead letter queue (DLQ). A message has been retried 5 times and lands in the DLQ. What should your ops team do?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Kafka vs RabbitMQ — you need to replay messages from 2 weeks ago for a new service. Which do you use and why?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Message ordering: you need all messages for a given user to be processed in order. How do you guarantee this in Kafka?', type: 'scenario', difficulty: 'Medium' },
    { q: 'A consumer is slow and takes 30 seconds to process one message. Kafka\'s max.poll.interval.ms is 10 seconds. What happens?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Consumer group rebalancing — describe what happens to message processing during a rebalance and how to minimize the impact.', type: 'edge-case', difficulty: 'Hard' },
    { q: 'You publish an event to a Kafka topic. 5 downstream services consume it. Two of them are down. How does Kafka handle this?', type: 'scenario', difficulty: 'Easy' },
    { q: 'You need sub-millisecond message delivery. Is Kafka the right choice? What alternative would you consider?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Idempotent consumers — your database write succeeded, but the consumer crashed before committing. It retries. How do you make the retry safe?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Message size: you publish 100MB video files to Kafka. What problems arise and how do you handle large payloads?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'Backpressure — a slow consumer causes the queue to fill up. What happens to the producer when the queue is full in RabbitMQ vs Kafka?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Compacted topics in Kafka — what are they, and when would you use one over a regular retention-based topic?', type: 'scenario', difficulty: 'Hard' },
    { q: 'You need to process 1 million messages per second. How do you design the partition count and consumer count?', type: 'scenario', difficulty: 'Hard' },
    { q: 'A message was processed but the downstream API call failed. The message offset is already committed. How do you handle this?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Fan-out pattern: one event needs to trigger 50 different consumers. Compare topic-per-consumer vs one topic with 50 consumer groups.', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your Kafka broker loses a partition leader. How does the cluster recover and what\'s the impact on producers and consumers?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Priority queues — Kafka doesn\'t natively support message priority. How would you implement priority processing?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Event ordering across multiple Kafka topics — how do you handle a case where Event A from Topic 1 must be processed before Event B from Topic 2?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Your team accidentally published sensitive PII to a Kafka topic. How do you handle this given Kafka\'s immutable log?', type: 'edge-case', difficulty: 'Medium' },
  ],

  'databases': [
    { q: 'You shard a users table by user_id. A "find all users in city X" query now needs to hit every shard. How do you handle cross-shard queries?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Your read replica is 10 seconds behind the primary. A user updates their password and immediately tries to log in — it fails. How do you fix this?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'SELECT * FROM orders WHERE status = \'pending\'. The table has 100M rows and 90% are pending. Your index on status is ignored. Why?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'ACID vs BASE — you\'re building a bank transfer feature. Which properties are non-negotiable, and what\'s your minimum acceptable consistency level?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Hot shard problem: 80% of your traffic hits 1 of your 10 shards because all new users start with id > 9000. How do you fix the sharding key?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Your PostgreSQL query uses ORDER BY + LIMIT 10 but it\'s slow even with an index. You check EXPLAIN and see a sequential scan. Why might the planner prefer this?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Two users simultaneously try to book the last seat on a flight. Walk me through the race condition and how you prevent double-booking.', type: 'scenario', difficulty: 'Medium' },
    { q: 'You need to store 1 billion time-series data points (sensor readings every second). Relational DB or something else — justify your choice.', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Connection pool exhaustion — your app has 1000 threads each trying to hold a DB connection. The pool has 100 connections. What symptoms appear and how do you fix it?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'You add a NOT NULL column to a 500M-row production table with zero downtime. Walk me through the migration strategy.', type: 'scenario', difficulty: 'Hard' },
    { q: 'N+1 query problem: you fetch 100 users then run a separate query per user to get their orders. How do you fix this at the application and database level?', type: 'scenario', difficulty: 'Easy' },
    { q: 'Multi-master replication — two nodes accept writes simultaneously. A user\'s balance is updated on Node A and Node B at the same time. How is the conflict resolved?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'You have a query running in a transaction for 30 minutes holding a row lock. Another query needs that row. What happens and how do you detect/prevent this?', type: 'scenario', difficulty: 'Medium' },
    { q: 'When would you choose a document database (MongoDB) over PostgreSQL, and what do you lose?', type: 'tradeoff', difficulty: 'Easy' },
    { q: 'Index on (user_id, created_at) vs separate indexes on each — when is the composite index better?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your database disk is 90% full. You can\'t add disk immediately. What can you do in the next 2 hours to buy time?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Cascading deletes — you delete a user and accidentally remove 10,000 related rows. How do you prevent this in production?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Explain the difference between optimistic and pessimistic locking with a concrete checkout example.', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your read replicas are overloaded but the primary is fine. The replica count is already at 5. What else can you do?', type: 'scenario', difficulty: 'Hard' },
    { q: 'MVCC (Multi-Version Concurrency Control) — why does PostgreSQL sometimes return a "snapshot" of old data even within a transaction?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'You store JSON blobs in a JSONB column for flexibility. Six months later queries on JSON fields are slow. What happened and how do you fix it?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Graph data in a relational DB — you have a social network friendship table. Finding "friends of friends" requires multiple self-joins. When do you move to a graph DB?', type: 'tradeoff', difficulty: 'Hard' },
  ],

  'cap-theorem': [
    { q: 'You\'re designing a payment system. During a network partition, would you rather reject writes (CP) or accept them and reconcile later (AP)? Justify your choice.', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Cassandra is labeled AP. Can you configure it to behave more like a CP system? How, and what do you sacrifice?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Your system is CA (consistent and available). Your interviewer says "CA systems don\'t really exist in distributed systems." Are they right? Why?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'A network partition happens between your primary and replica databases. You\'re AP. Describe what "stale reads" look like to the end user.', type: 'scenario', difficulty: 'Medium' },
    { q: 'What is the PACELC theorem and why does it matter more for most production decisions than the original CAP theorem?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Eventual consistency: you update your Twitter bio. A user in Tokyo sees your old bio for 3 seconds. Is this a CAP violation? Why or why not?', type: 'edge-case', difficulty: 'Easy' },
    { q: 'DynamoDB lets you configure per-request consistency level. Strong consistency doubles the read cost. When would you pay for it?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Linearizability vs sequential consistency vs eventual consistency — rank them by strength and give a real-world analogy for each.', type: 'scenario', difficulty: 'Hard' },
    { q: 'You are building a shopping cart. During a partition, a user adds an item. Should you allow or reject it? What are the consequences of each?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Zookeeper is CP. What happens to Zookeeper clients during a partition where the leader is isolated in the minority partition?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'How does Google Spanner achieve "external consistency" while being distributed globally? What\'s the key innovation?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Your microservices each have their own database. Service A calls Service B which updates its DB. Service A\'s DB is still on the old state. Which CAP choice did you make?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'Vector clocks — how do they help with conflict resolution in an AP system, and what information do they capture?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Two nodes accept writes during a partition. When the partition heals, they have conflicting values for the same key. Name three conflict resolution strategies.', type: 'edge-case', difficulty: 'Hard' },
    { q: 'A user\'s balance read from Replica A shows $100. The same read from Replica B shows $95. Both are correct at their snapshot time. Is this a bug?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'Why can\'t you have all three of CAP simultaneously? Give the simplest possible proof or example.', type: 'scenario', difficulty: 'Easy' },
    { q: 'Read-your-writes consistency — which consistency model is this, and does it require CP or can AP systems provide it?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'etcd vs Consul for service discovery — both are CP. What happens to service registration during a 3-node cluster with 2-node failure?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Your analytics dashboard shows metrics that are 5 minutes stale. Is this an eventual consistency issue or a system design choice? How would you explain this to a non-technical stakeholder?', type: 'scenario', difficulty: 'Easy' },
    { q: 'CRDTs (Conflict-free Replicated Data Types) — how do they sidestep CAP trade-offs, and for what data types are they applicable?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A distributed counter (e.g., "likes" on a post). You want AP but also want to avoid negative like counts. How?', type: 'edge-case', difficulty: 'Hard' },
  ],

  'rate-limiting': [
    { q: 'You implement per-user rate limiting: 100 requests/minute. A user creates 1000 bot accounts. What secondary defense is needed?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Your rate limiter uses Redis INCR + TTL. The Redis node fails and is temporarily unavailable. Do you fail open (allow all requests) or fail closed (block all)?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Fixed window counter — boundary attack: explain precisely how a user can double their effective rate limit and how sliding window prevents it.', type: 'gotcha', difficulty: 'Medium' },
    { q: 'You have 50 API servers each with a local rate limiter. What\'s the maximum rate a single user could achieve, and how do you fix this?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Token bucket vs leaky bucket — a user sends 10 messages/second for 3 seconds then nothing. Under each algorithm, how many messages are delivered?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Sliding window log stores every request timestamp. At 100K users each doing 1000 requests/minute, calculate the memory usage. Is this feasible?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'A user\'s API call gets rate limited. They receive 429. Their retry logic retries immediately in a loop. How do you prevent retry storms?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Tiered rate limits: free users get 100/min, paid users get 10000/min. How do you implement this without separate Redis namespaces per tier?', type: 'scenario', difficulty: 'Medium' },
    { q: 'You need to rate limit by user ID, IP, and API key simultaneously. How do you combine multiple limits without making 3 Redis calls per request?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Rate limiting at the API gateway vs in each microservice — what are the pros and cons of each placement?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A user bursts 1000 requests in 1 second, consuming their whole minute budget. They must now wait the full minute with zero remaining. How does this affect user experience and how do you smooth it?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'You rate limit by IP but your users are behind a corporate NAT and share one IP. 1000 employees all get blocked together. How do you handle this?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Distributed sliding window counter — Redis GETSET vs Redis scripted atomic operations vs Redis Streams for implementing this. Which is most accurate?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Your rate limiter adds 2ms latency per request. At 500K RPS, calculate the CPU cost. Is this acceptable?', type: 'scenario', difficulty: 'Hard' },
    { q: 'A web scraper hits your API at exactly 99 requests/minute to stay just under your 100/minute limit. How do you detect and handle sophisticated abusers?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Rate limiting write operations differently from read operations — when and why would you apply asymmetric limits?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Burst allowance: you want 100 requests/minute long-term but allow up to 200 in any single second. Which algorithm handles this and how do you configure it?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Your CDN sits in front of your API and strips the original client IP. Your rate limiter sees the CDN\'s IP. How do you rate limit the real user?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'How would you implement rate limiting for a GraphQL API where a single query can be arbitrarily expensive?', type: 'scenario', difficulty: 'Hard' },
    { q: 'A DDoS attack sends 10M requests/second. Your rate limiter is overwhelmed — it can\'t even check limits fast enough. What defenses exist upstream?', type: 'edge-case', difficulty: 'Hard' },
  ],

  'circuit-breaker': [
    { q: 'Service A calls Service B. B is down. A\'s thread pool fills with waiting requests. Describe the cascade failure step by step.', type: 'scenario', difficulty: 'Medium' },
    { q: 'You set the circuit breaker threshold to "open after 5 failures." Service B is flaky — alternating success/failure. The breaker never opens. How do you fix the configuration?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'The circuit is Half-Open. You send a probe request. It succeeds. You close the circuit. The next 100 requests all fail. What was wrong with the Half-Open → Closed logic?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Your fallback returns a cached value when the circuit is open. The cache is 2 hours stale. Is this acceptable for a product recommendations service vs. a bank balance?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A circuit breaker per dependency — you have 20 microservices, each calling 5 others. How many breakers do you need and who owns them?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Service B is slow (5s response) but not down. The circuit breaker only tracks failures. It stays closed while threads exhaust. How do you catch slow dependencies?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'You deploy a new version of Service B with a bug. The circuit breaker opens. How do you roll back without waiting for the Open timeout to expire?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Hystrix vs Resilience4j vs manual implementation — what key features does a library give you that a simple "catch exception and count" doesn\'t?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Two services both have circuit breakers protecting calls to each other. Service A\'s breaker opens for B, and B\'s breaker opens for A. What\'s the recovery path?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'You have 10 instances of Service A, each with their own circuit breaker for Service B. 3 instances have open circuits, 7 have closed. Users get inconsistent behavior. How do you coordinate state?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'A database migration causes Service B to return 500s for 2 minutes. The circuit opens. After recovery, Service B is healthy but the circuit stays open for 30s. How does this affect the SLA?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Bulkhead + Circuit Breaker together — explain how they provide different types of protection and why you\'d want both.', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A circuit breaker is tripped by a 429 (rate limit) response. Should rate-limit responses count toward the failure threshold? Justify your answer.', type: 'gotcha', difficulty: 'Hard' },
    { q: 'You\'re building a checkout service that calls: inventory, payment, shipping (in order). Which calls get circuit breakers and what\'s the fallback for each?', type: 'scenario', difficulty: 'Medium' },
    { q: 'The circuit breaker opens for your email notification service. Orders still complete but users don\'t get confirmation emails. How do you alert the ops team and recover the missed emails?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Half-Open state probe request — should you send one probe or multiple? What are the tradeoffs of each approach?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Your circuit breaker collects metrics: total calls, failures, latency percentiles. What dashboard would you build to monitor circuit health in production?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Thread pool isolation vs semaphore-based circuit breakers — when would you choose semaphores despite their limitations?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A 3rd-party payment API has 99.9% uptime. You don\'t have a circuit breaker. Calculate the expected cascade impact on a service with 50 concurrent users if the payment API stalls for 10 seconds.', type: 'scenario', difficulty: 'Hard' },
    { q: 'Circuit breaker state (open/closed/half-open) should be stored where — in-memory per instance or shared in Redis? Tradeoffs?', type: 'tradeoff', difficulty: 'Hard' },
  ],

  'cqrs': [
    { q: 'Your CQRS read model is 3 seconds behind the write model. A user creates an order then immediately views their order history — the new order isn\'t there. How do you handle this UX?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'You have 15 different read models for 15 different queries. A new field is added to the write model. How many projections need to be updated?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'CQRS without Event Sourcing — how do you keep the read model in sync if you only have the current state in the write model?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A critical bug causes your CQRS read model to produce wrong data for 4 hours. How do you detect this and repair it?', type: 'scenario', difficulty: 'Hard' },
    { q: 'You\'re building an e-commerce platform. Name 3 specific use cases where CQRS adds clear value and 2 where it\'s overkill.', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Command validation — the command is "PlaceOrder" but the item is out of stock. Should validation happen in the Command Handler or before it? What\'s the risk of each?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Your read model is a pre-computed feed table. A user with 10M followers posts a message. How do you handle the fan-out write to the read model?', type: 'scenario', difficulty: 'Hard' },
    { q: 'CQRS + microservices: the write service and read service are separate deployments. How do you ensure the read model is updated atomically with the write?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'You implement CQRS with a message bus. The bus goes down for 5 minutes. What happens to your read models and how do you recover?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'A business analyst wants to query: "all orders where the total changed more than 3 times." How does CQRS with Event Sourcing make this query possible vs. impossible with CRUD?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Scaling CQRS independently — your read load is 100× write load. What does CQRS make architecturally possible that a monolith doesn\'t?', type: 'tradeoff', difficulty: 'Easy' },
    { q: 'A command changes state but the projection worker is behind. A second command depends on the result of the first. What\'s the ordering guarantee?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'You have a CQRS system with 5 read models. You decide to add a 6th for a new reporting feature. How do you bootstrap it with historical data?', type: 'scenario', difficulty: 'Medium' },
    { q: 'CQRS read model in Elasticsearch vs PostgreSQL — when would you choose each for the query side?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A user submits a command and polls for the result. The read model is eventually consistent. How do you implement the "wait for my own update" pattern?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Domain events vs integration events in CQRS — what\'s the difference and why does it matter for coupling?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Your CQRS system has 200 event types after 2 years of development. A new developer joins. How do you manage the complexity?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Can you implement CQRS in a monolith, or does it require microservices? Give a concrete example.', type: 'gotcha', difficulty: 'Easy' },
    { q: 'Sagas + CQRS: a saga spans 4 services. How do the CQRS read models across those 4 services stay coordinated during a compensating transaction?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Testing CQRS — how do you write an integration test that verifies a command correctly updates the read model with eventual consistency?', type: 'edge-case', difficulty: 'Hard' },
  ],

  'event-sourcing': [
    { q: 'An event log has 10M events. Loading current state requires replaying all of them. Your service takes 4 minutes to start. How do you fix this?', type: 'scenario', difficulty: 'Medium' },
    { q: 'You deployed code with a bug that emitted wrong events for 1 hour. The event log is immutable. How do you fix the state without deleting events?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Event schema evolution: you rename a field in your "OrderPlaced" event. You have 5 years of old events with the old field name. How do you handle this?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'You need to answer "what was the state of account X at 3:00 PM on January 15, 2022?" How does Event Sourcing make this possible?', type: 'scenario', difficulty: 'Easy' },
    { q: 'Snapshot frequency tradeoff: snapshot every event vs every 1000 events. What are the storage and replay performance implications of each extreme?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Two concurrent commands update the same aggregate. Both read the state at version 5 and try to emit events at version 6. How do you prevent this?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Your event store has 1TB of data. A new projection needs to be built from all historical events. How long does this take and what are the infrastructure implications?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Event Sourcing forces you to never delete data. A user requests GDPR deletion of their personal data. How do you comply?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Why is "event" different from "state change record"? What must an event represent semantically?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your event store is the "source of truth" but your SQL read model is corrupted. You rebuild it from events — it takes 6 hours. During this time, can users still write?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Temporal queries: using Event Sourcing, how do you efficiently answer "how many users signed up in Q3 2023 who are still active?"', type: 'scenario', difficulty: 'Hard' },
    { q: 'Event Sourcing + CQRS vs just CQRS without event sourcing — what does Event Sourcing add beyond being able to build projections?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Large events vs small events — should an "OrderUpdated" event contain the full order state or just the delta?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your aggregate emits 20 events per command. After 1 year, replaying from scratch takes 30 minutes per aggregate instance. What strategies reduce replay time?', type: 'scenario', difficulty: 'Hard' },
    { q: 'A bank account aggregate can\'t go below $0. How do you enforce this invariant when two concurrent "Withdraw" commands both read a balance of $50 and both try to withdraw $40?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Sagas in Event Sourcing — how does an event-sourced saga know which step to execute next after a crash and restart?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Process managers vs sagas in an event-sourced system — what\'s the naming difference and when does each term apply?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'You need to query "find all users whose last event was more than 90 days ago." How do you build this efficiently from an event log?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Event versioning: V1 of "OrderPlaced" has 5 fields. V2 has 8. Your aggregate handler must support both. How do you implement the migration logic?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Is Event Sourcing suitable for a high-frequency trading system processing 1M trades/second? What are the bottlenecks?', type: 'tradeoff', difficulty: 'Hard' },
  ],

  'saga-pattern': [
    { q: 'Order → Reserve Inventory → Charge Payment → Ship. Payment fails. Write all compensating transactions in order.', type: 'scenario', difficulty: 'Medium' },
    { q: 'Choreography vs Orchestration: you have a saga spanning 8 services. Which approach becomes harder to debug as the number of services grows?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A compensating transaction itself fails. You\'re 3 steps into a 5-step saga rollback. What happens to the intermediate state?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Saga isolation: another transaction reads inventory in the middle of your saga before the compensation runs. They see "reserved" inventory that will be released. What anomaly is this?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'You implement a saga with a message bus. The bus delivers the "InventoryReserved" event twice. How does your saga handle duplicate events?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Saga vs 2PC for distributed transactions — why does the industry prefer saga for microservices despite its weaker guarantees?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A saga timeout — "ChargePayment" takes too long (no response). The saga has no way to know if payment succeeded. How do you handle this ambiguous state?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Saga state machine — describe the states a saga transitions through from start to either successful completion or rollback.', type: 'scenario', difficulty: 'Medium' },
    { q: 'You have a hotel booking saga: reserve room → charge card → confirm reservation. The hotel reservation system is down for maintenance for 2 hours. How does the saga wait?', type: 'scenario', difficulty: 'Hard' },
    { q: 'A choreography saga has 6 services publishing events. How do you get a full view of a saga\'s progress across all 6 for debugging?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Semantic lock countermeasure — how does it reduce the isolation anomaly in sagas, and what\'s the cost?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'You need a saga to handle "reserve item for 15 minutes, then release if not purchased." How do you implement the time-based release?', type: 'scenario', difficulty: 'Medium' },
    { q: 'A saga completes successfully but the "send confirmation email" step fails silently. The user never gets an email. How do you detect this and retry?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Orchestration saga: the orchestrator crashes mid-saga. How does it know which step to resume from after restart?', type: 'scenario', difficulty: 'Hard' },
    { q: 'An airline booking saga: reserve flight A + reserve flight B + charge. Flight A is reserved but Flight B is unavailable. The compensation must release Flight A. What if Flight A\'s reservation system is also down during compensation?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Can you use sagas for read operations, or is it only for writes? Justify your answer.', type: 'tradeoff', difficulty: 'Easy' },
    { q: 'Testing sagas — how do you write an integration test that verifies the saga correctly rolls back after a failure in step 3 of a 5-step saga?', type: 'scenario', difficulty: 'Hard' },
    { q: 'You have 1000 concurrent sagas running. Your orchestrator is a single service. How do you scale it without losing saga state?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Long-running sagas (days/weeks) — a travel booking holds resources for 7 days. How do you handle it differently from a 5-second checkout saga?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A saga is partially committed across 3 services. A developer does a hotfix that changes the data schema. Old sagas in-flight can no longer deserialize their state. What happens?', type: 'gotcha', difficulty: 'Hard' },
  ],

  'outbox-pattern': [
    { q: 'You write to the DB and publish to Kafka in sequence. The app crashes between the two operations. What happens to the event? How does the outbox pattern prevent this?', type: 'scenario', difficulty: 'Easy' },
    { q: 'Your outbox relay publishes the same event twice (crash after publish, before marking sent). How does the consumer handle this?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Polling the outbox table every 100ms vs using CDC (Change Data Capture). What are the tradeoffs in latency, database load, and operational complexity?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your outbox table has accumulated 10 million unpublished rows because the relay was down for a week. How do you recover without overwhelming the message broker?', type: 'scenario', difficulty: 'Hard' },
    { q: 'You use the outbox pattern with DynamoDB. DynamoDB supports conditional writes but not multi-table transactions. How do you implement the outbox atomically?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'The outbox relay is a background thread in the same process as your app. The process gets a SIGKILL. The outbox event is in-flight. What happens?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'CDC-based outbox with Debezium tailing the PostgreSQL WAL. Your database disk is full and WAL archiving fails. What\'s the impact on Debezium?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Outbox pattern guarantees at-least-once delivery. Your consumer sees the same order event 3 times and charges the customer 3 times. Whose responsibility is idempotency?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'You need strict event ordering: Event A for order #123 must be published before Event B for order #123. How does your outbox design guarantee ordering per aggregate?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Outbox table grows indefinitely. Design a cleanup strategy that doesn\'t delete events that haven\'t been published yet.', type: 'scenario', difficulty: 'Medium' },
    { q: 'You have 50 microservices each with their own outbox table. Monitoring question: how do you alert when an outbox relay falls behind?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Transactional outbox with a NoSQL database that doesn\'t support transactions. What alternative pattern achieves atomic write + event publication?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Your outbox relay must process events in order per aggregate. How do you parallelize processing across multiple aggregates without breaking per-aggregate ordering?', type: 'scenario', difficulty: 'Hard' },
    { q: 'A message broker is down for 4 hours. Your outbox accumulates events. When the broker recovers, 200K events need to be published. What\'s the replay strategy?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Two-phase outbox: the relay publishes to Kafka but the Kafka commit hasn\'t been confirmed yet. The relay crashes. How do you avoid both duplication and data loss?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'The outbox event contains the entity ID but not the full entity state. The consumer must query the database to get current state. What race condition exists?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Thick events (contain full state) vs thin events (contain only ID) in the outbox — when would you choose each?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'You want to publish events to both Kafka and an S3 archive. How does the outbox pattern need to be modified to support fan-out to multiple destinations?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Your outbox relay uses SELECT FOR UPDATE to claim rows. At 1000 events/second with 5 relay workers, how does contention affect throughput?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Outbox pattern in a serverless (Lambda) environment — the function is stateless and short-lived. How do you implement the relay?', type: 'tradeoff', difficulty: 'Hard' },
  ],

  'observability': [
    { q: 'Your p99 latency is 3 seconds but p50 is 50ms. What does this tell you and how do you find the root cause?', type: 'scenario', difficulty: 'Medium' },
    { q: 'An alert fires at 3am. You have logs, metrics, and traces. Walk me through the first 5 minutes of incident investigation in order.', type: 'scenario', difficulty: 'Medium' },
    { q: 'A service has 99.9% success rate but users are complaining. What might the metrics be missing?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'Your error rate alert fires if error rate > 1% for 5 minutes. A 2-minute spike to 50% errors fires no alert. What\'s wrong with the alerting configuration?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Distributed tracing: a request goes through 5 services and takes 800ms total. How do you identify which service contributed the most latency?', type: 'scenario', difficulty: 'Easy' },
    { q: 'You add a new metric to your service. 6 months later it\'s never been queried. What process is missing in your observability practice?', type: 'gotcha', difficulty: 'Easy' },
    { q: 'Alert fatigue: your on-call team receives 500 alerts per week. 90% are noise. How do you reduce alerts without missing real incidents?', type: 'scenario', difficulty: 'Hard' },
    { q: 'You deploy a new service version. Error rate goes from 0.1% to 0.15%. Is this statistically significant? How do you decide whether to rollback?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Cardinality explosion: you add a "user_id" label to a Prometheus metric. You have 10M users. What happens to your metrics storage?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'A database query works fine in staging (100 rows) but is slow in production (100M rows). Your staging observability didn\'t catch this. What monitoring gap exists?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'SLO-based alerting: you have 99.9% uptime SLO. How do you alert when you\'re burning through your error budget too fast, before you actually breach the SLO?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Your monitoring system is down during an incident. You\'re "flying blind." What manual observability methods can you fall back to?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Sampling traces at 1% in production — you miss rare errors that only occur 0.01% of the time. How do you instrument for these edge cases?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A "zombie" service: CPU is idle, no errors, but users can\'t use it. What type of monitoring would catch this and how?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Structured logging vs unstructured: your logs contain "User 12345 failed" — how does this affect your ability to alert and query at scale?', type: 'tradeoff', difficulty: 'Easy' },
    { q: 'You need to correlate a user complaint ("my request at 14:37 was slow") with logs and traces. Walk me through the full investigation path.', type: 'scenario', difficulty: 'Medium' },
    { q: 'Your service makes 3 external API calls per request. One is slow intermittently. How does distributed tracing help isolate this vs. looking at per-service latency graphs?', type: 'scenario', difficulty: 'Medium' },
    { q: 'The correct SLI for "is the checkout working?" — should it be HTTP 200 rate, checkout completion rate, or payment success rate? What\'s the difference?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A memory leak causes OOM crashes every 48 hours. Your alerting fires on the crash but not on the gradual memory growth. How do you catch this earlier?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Your observability stack itself (Prometheus, Elasticsearch) starts consuming 30% of your infrastructure budget. How do you right-size it?', type: 'scenario', difficulty: 'Hard' },
  ],

  'consensus': [
    { q: 'A 5-node Raft cluster. 3 nodes fail simultaneously. The remaining 2 can\'t form quorum. What happens to reads and writes?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Network partition: 2 nodes on the left, 3 on the right. The leader is on the left. What happens when the leader on the left tries to commit a write?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Raft leader election: two candidates start an election simultaneously. Walk me through how exactly one winner is guaranteed.', type: 'scenario', difficulty: 'Hard' },
    { q: 'etcd is at the heart of Kubernetes. etcd is CP. What happens to Kubernetes during an etcd leader election (which takes ~150ms)?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Log compaction in Raft: a new node joins the cluster. The log has 10M entries. How does the new node catch up without replaying all 10M entries?', type: 'scenario', difficulty: 'Hard' },
    { q: 'A Raft leader commits a log entry to a quorum of followers, then crashes before sending the commit notification to the client. What does the client observe?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Paxos vs Raft — both achieve consensus. Why did the industry mostly adopt Raft for new implementations?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'You have a 3-node cluster. You want to add 2 more nodes for better fault tolerance. During the addition of the 4th node (before 5th is up), you temporarily have a 4-node cluster. What\'s the quorum requirement and the fault tolerance?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'A stale leader (network partition healed, old leader rejoins) tries to commit entries. How does Raft\'s term system prevent it from causing split-brain?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Read performance in Raft: all reads must go to the leader to guarantee linearizability. How does this create a hotspot, and what can you do about it?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'ZooKeeper uses ZAB (ZooKeeper Atomic Broadcast) instead of Raft. What problem does ZAB solve that vanilla Paxos doesn\'t?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Why is a 2-node Raft cluster LESS fault tolerant than a single node? Explain the quorum math.', type: 'gotcha', difficulty: 'Medium' },
    { q: 'Your distributed database uses Raft for replication. A "slow follower" is always 2 seconds behind the leader. What happens to write latency?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Leader leases — how do they allow followers to serve reads without contacting the leader, while still providing linearizability?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Multi-Raft: CockroachDB uses multiple Raft groups, one per data range. Why is one global Raft group insufficient for a distributed database?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Clock drift in distributed consensus: why is physical time unreliable for ordering events, and what does TrueTime (Google Spanner) do differently?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'A Raft cluster loses quorum. Some application teams want "read-only mode" to serve stale reads. Is this safe? What guarantees do you give up?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Byzantine fault tolerance vs crash fault tolerance — Raft handles crash faults. Give a scenario where you need BFT and why Raft is insufficient.', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Consensus overhead: a 3-node Raft cluster requires 2 round trips per write (append + commit). At 10,000 writes/second with 2ms network RTT, what\'s the theoretical max throughput?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Service discovery using Raft-based etcd is CP. During an election, new service registrations fail. What\'s the impact on a Kubernetes pod startup?', type: 'gotcha', difficulty: 'Hard' },
  ],

  'cdn': [
    { q: 'A user uploads a video to S3. You want it globally available within 60 seconds. How does CDN replication work across PoPs?', type: 'scenario', difficulty: 'Medium' },
    { q: 'You deploy a hotfix. The CDN still serves the old JS bundle to 80% of users. Cache TTL is 24 hours. You need the fix live now. What are your options?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Cache-busting via filename hashing (bundle.abc123.js) vs versioned URLs (/v2/bundle.js) — what are the tradeoffs for CDN cache invalidation?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A user in Tokyo requests a 4K video hosted in US-East. The CDN PoP in Tokyo doesn\'t have it cached. Walk through every network hop.', type: 'scenario', difficulty: 'Easy' },
    { q: 'Edge computing at CDN PoPs (Cloudflare Workers, Lambda@Edge) — give me a use case where running logic at the edge is strictly better than at origin.', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Your CDN hit rate is 30% for a high-traffic product page. Diagnose at least 3 reasons why it might be so low.', type: 'scenario', difficulty: 'Medium' },
    { q: 'Origin shielding: instead of all 200 PoPs pulling from origin on cache misses, they pull from one shield PoP. What happens if the shield PoP goes down?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'A CDN serves your API responses. A bug causes incorrect API data. You fix it at origin. How long until all CDN edge nodes serve the correct response?', type: 'scenario', difficulty: 'Medium' },
    { q: 'Cache poisoning attack: a malicious request tricks your CDN into caching a malicious response for a popular URL. How do you prevent and detect this?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Vary header: your API returns different responses based on Accept-Language. A CDN naively caches the first response. French users get English. How do you fix this?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Dynamic vs static content CDN caching — your homepage is personalized per user. Can you CDN-cache it? What techniques exist?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'You\'re live-streaming a sporting event. 5 million viewers tune in at kickoff. How does CDN handle the concurrent request storm?', type: 'scenario', difficulty: 'Hard' },
    { q: 'HTTPS at the CDN edge: TLS termination at the PoP vs pass-through to origin. When would you choose pass-through despite the performance cost?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A CDN purge takes 30 seconds to propagate globally. During those 30 seconds, some users get stale content and others get fresh. Is this acceptable and what user-facing issues can arise?', type: 'edge-case', difficulty: 'Medium' },
    { q: 'Geo-restriction: you must not serve content to users in Country X due to legal reasons. How do you implement this at the CDN layer?', type: 'scenario', difficulty: 'Easy' },
    { q: 'CDN provider outage (e.g., Fastly 2021). Your entire website goes down because DNS points to the CDN. How do you architect for CDN failover?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Hot object thundering herd at the CDN: 1M users simultaneously request a new release that isn\'t cached yet. How does CDN request coalescing/collapsing work?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Stale-while-revalidate: the CDN returns a cached response immediately while fetching a fresh one in the background. What\'s the user experience impact?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your CDN logs show that 40% of requests are cache MISS for a supposedly static image. Investigation shows the ETag changes on every origin request. What\'s the bug?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Multi-CDN strategy: you use both Cloudflare and Akamai. How do you route traffic between them and what triggers a failover?', type: 'tradeoff', difficulty: 'Hard' },
  ],

  'service-discovery': [
    { q: 'Service A needs to call Service B. Service B has 10 instances. Walk me through client-side service discovery vs server-side, and which adds coupling to the caller.', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your service registry (Consul) is CP. During a leader election, new service registrations fail for 200ms. What happens to services trying to start up during this window?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'A service instance crashes but doesn\'t deregister itself. The registry still lists it as healthy. How long before other services stop calling it?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'DNS-based service discovery vs a dedicated registry (Consul/Eureka) — what does DNS lack that a dedicated registry provides?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Blue-green deployment with service discovery: how do you route 10% of traffic to the green instances while keeping 90% on blue?', type: 'scenario', difficulty: 'Medium' },
    { q: 'A microservice starts up and registers with Consul before its database connection is ready. Health checks pass. It starts receiving traffic and returns 500s. How do you fix registration timing?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Kubernetes uses etcd for service discovery internally. A pod restarts and gets a new IP. How does service discovery update without any manual intervention?', type: 'scenario', difficulty: 'Easy' },
    { q: 'Service mesh (Istio/Linkerd) vs explicit service discovery client — what does a service mesh abstract away that you\'d otherwise have to code yourself?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Circuit breaker + service discovery: a service is registered as healthy but is actually slow. How do client-side circuit breakers complement health-check-based discovery?', type: 'scenario', difficulty: 'Hard' },
    { q: 'You have 500 services in your registry and each queries the registry every 10 seconds. Calculate the query load on the registry. Is this a scaling concern?', type: 'gotcha', difficulty: 'Medium' },
    { q: 'TTL-based deregistration vs active health checks — which is safer for ensuring stale instances are removed quickly? What are the tradeoffs?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A service is deployed in 3 regions. How does cross-region service discovery work without a globally distributed registry?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Sidecar proxy pattern (Envoy) — how does it handle service discovery differently from a library embedded in the application?', type: 'tradeoff', difficulty: 'Hard' },
    { q: 'Service versioning in discovery: you deploy v2 of a service alongside v1. How does the registry represent both versions and how do callers know which to call?', type: 'edge-case', difficulty: 'Hard' },
    { q: 'Your registry has 10,000 service instances (large microservices org). What\'s the memory and CPU cost to store all instance data?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Multicast DNS vs unicast DNS for service discovery — when would you use each in a microservices environment?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'A service instance is registered but behind a NAT. The registered IP is a private IP that isn\'t routable from other services. How do you handle this?', type: 'gotcha', difficulty: 'Hard' },
    { q: 'Canary releases with service discovery: you want 5% of calls to go to the canary instance. How do you implement traffic weights in the discovery layer?', type: 'scenario', difficulty: 'Hard' },
    { q: 'Health check depth: a shallow health check (HTTP 200) vs a deep health check (queries the database). What\'s the tradeoff for service discovery?', type: 'tradeoff', difficulty: 'Medium' },
    { q: 'Your service discovery relies on Kubernetes DNS. You have a pod with a 30-second startup time but the DNS record propagates immediately. How do you prevent premature traffic?', type: 'edge-case', difficulty: 'Medium' },
  ],
}
