export type TopicCategory = 'Distributed Systems' | 'Design Patterns' | 'API & Networking' | 'Cloud'
export type TopicDifficulty = 'Beginner' | 'Intermediate' | 'Advanced'

export interface Topic {
  slug: string
  title: string
  description: string
  category: TopicCategory
  difficulty: TopicDifficulty
  minutes: number
  concepts: string[]
  hasContent: boolean   // true = /learn/:slug page exists
  color: string
}

export const TOPICS: Topic[] = [
  // ── Distributed Systems ──────────────────────────────────────
  {
    slug: 'load-balancing',
    title: 'Load Balancing',
    description: 'Distribute traffic across servers, eliminate single points of failure, and handle node failures gracefully.',
    category: 'Distributed Systems',
    difficulty: 'Beginner',
    minutes: 15,
    concepts: ['Round-robin', 'Consistent hashing', 'L4 vs L7', 'Health checks'],
    hasContent: true,
    color: '#3b82f6',
  },
  {
    slug: 'caching',
    title: 'Redis & Caching',
    description: 'Speed up reads by 10–100x, reduce database pressure, and learn cache invalidation strategies.',
    category: 'Distributed Systems',
    difficulty: 'Beginner',
    minutes: 20,
    concepts: ['Cache-aside', 'Write-through', 'TTL strategies', 'Cache stampede'],
    hasContent: true,
    color: '#eab308',
  },
  {
    slug: 'queues',
    title: 'Message Queues',
    description: 'Decouple services with async messaging, handle backpressure, and build event-driven systems.',
    category: 'Distributed Systems',
    difficulty: 'Intermediate',
    minutes: 25,
    concepts: ['Kafka partitions', 'Consumer groups', 'At-least-once', 'Dead letter queues'],
    hasContent: true,
    color: '#a855f7',
  },
  {
    slug: 'databases',
    title: 'Databases Deep Dive',
    description: 'Master SQL vs NoSQL tradeoffs, horizontal sharding, replication, and query optimization.',
    category: 'Distributed Systems',
    difficulty: 'Intermediate',
    minutes: 30,
    concepts: ['Sharding strategies', 'Replication', 'ACID vs BASE', 'Read replicas'],
    hasContent: true,
    color: '#22c55e',
  },
  {
    slug: 'cap-theorem',
    title: 'CAP Theorem',
    description: 'Understand the fundamental constraints of distributed systems: consistency, availability, partition tolerance.',
    category: 'Distributed Systems',
    difficulty: 'Advanced',
    minutes: 20,
    concepts: ['CP vs AP systems', 'PACELC theorem', 'Consistency models', 'Network partitions'],
    hasContent: true,
    color: '#f97316',
  },
  {
    slug: 'rate-limiting',
    title: 'Rate Limiting',
    description: 'Protect your APIs from abuse, implement fair usage policies, and handle burst traffic gracefully.',
    category: 'Distributed Systems',
    difficulty: 'Intermediate',
    minutes: 20,
    concepts: ['Token bucket', 'Sliding window', 'Fixed window', 'Distributed rate limits'],
    hasContent: false,
    color: '#06b6d4',
  },
  {
    slug: 'cdn',
    title: 'CDN & Content Delivery',
    description: 'Serve static and dynamic content globally with low latency using edge caching and PoP strategies.',
    category: 'Distributed Systems',
    difficulty: 'Beginner',
    minutes: 15,
    concepts: ['Edge nodes', 'Cache invalidation', 'Origin pull', 'Anycast routing'],
    hasContent: false,
    color: '#10b981',
  },
  {
    slug: 'consensus',
    title: 'Distributed Consensus',
    description: 'Learn how distributed systems agree on values using Raft, Paxos, and leader election algorithms.',
    category: 'Distributed Systems',
    difficulty: 'Advanced',
    minutes: 35,
    concepts: ['Raft algorithm', 'Leader election', 'Paxos', 'Split-brain prevention'],
    hasContent: false,
    color: '#f43f5e',
  },
  {
    slug: 'observability',
    title: 'Monitoring & Observability',
    description: 'Build production-grade systems with metrics, traces, logs, and alerting to diagnose issues fast.',
    category: 'Distributed Systems',
    difficulty: 'Intermediate',
    minutes: 20,
    concepts: ['Metrics vs logs', 'Distributed tracing', 'SLO/SLA/SLI', 'Alert fatigue'],
    hasContent: false,
    color: '#8b5cf6',
  },
  {
    slug: 'service-discovery',
    title: 'Service Discovery',
    description: 'Enable microservices to find each other dynamically using service registries and health-aware routing.',
    category: 'Distributed Systems',
    difficulty: 'Intermediate',
    minutes: 20,
    concepts: ['Client-side discovery', 'Server-side discovery', 'Health checks', 'Consul / Eureka'],
    hasContent: false,
    color: '#ec4899',
  },

  // ── Design Patterns ──────────────────────────────────────────
  {
    slug: 'cqrs',
    title: 'CQRS Pattern',
    description: 'Separate read and write models to scale them independently and optimize each path for its workload.',
    category: 'Design Patterns',
    difficulty: 'Intermediate',
    minutes: 25,
    concepts: ['Command model', 'Query model', 'Read replicas', 'Eventual consistency'],
    hasContent: false,
    color: '#6366f1',
  },
  {
    slug: 'event-sourcing',
    title: 'Event Sourcing',
    description: 'Store state as an immutable sequence of events instead of current snapshots — enabling full audit trails and replay.',
    category: 'Design Patterns',
    difficulty: 'Advanced',
    minutes: 30,
    concepts: ['Event log', 'Snapshots', 'Projections', 'Temporal queries'],
    hasContent: false,
    color: '#0ea5e9',
  },
  {
    slug: 'circuit-breaker',
    title: 'Circuit Breaker',
    description: 'Prevent cascading failures in microservices by stopping calls to failing dependencies automatically.',
    category: 'Design Patterns',
    difficulty: 'Intermediate',
    minutes: 15,
    concepts: ['Open / Closed / Half-open', 'Failure threshold', 'Fallback logic', 'Hystrix / Resilience4j'],
    hasContent: false,
    color: '#ef4444',
  },
  {
    slug: 'saga-pattern',
    title: 'Saga Pattern',
    description: 'Manage distributed transactions across microservices without two-phase commit using compensating actions.',
    category: 'Design Patterns',
    difficulty: 'Advanced',
    minutes: 30,
    concepts: ['Choreography', 'Orchestration', 'Compensating transactions', 'Rollback strategies'],
    hasContent: false,
    color: '#f59e0b',
  },
  {
    slug: 'outbox-pattern',
    title: 'Outbox Pattern',
    description: 'Guarantee exactly-once event publishing by writing events to a database outbox before sending to a queue.',
    category: 'Design Patterns',
    difficulty: 'Advanced',
    minutes: 20,
    concepts: ['Transactional outbox', 'CDC polling', 'Idempotency keys', 'At-least-once delivery'],
    hasContent: false,
    color: '#14b8a6',
  },
  {
    slug: 'bulkhead',
    title: 'Bulkhead & Isolation',
    description: 'Isolate failures in one part of your system from spreading to others using resource pools and limits.',
    category: 'Design Patterns',
    difficulty: 'Intermediate',
    minutes: 15,
    concepts: ['Thread pool isolation', 'Process isolation', 'Semaphore limits', 'Failure domains'],
    hasContent: false,
    color: '#78716c',
  },
  {
    slug: 'strangler-fig',
    title: 'Strangler Fig Pattern',
    description: 'Incrementally migrate a monolith to microservices by routing traffic piece-by-piece to new services.',
    category: 'Design Patterns',
    difficulty: 'Intermediate',
    minutes: 15,
    concepts: ['Traffic routing', 'Facade layer', 'Incremental migration', 'Dark launch'],
    hasContent: false,
    color: '#84cc16',
  },

  // ── API & Networking ─────────────────────────────────────────
  {
    slug: 'api-design',
    title: 'API Design',
    description: 'Design clean, versioned, and backward-compatible REST and GraphQL APIs that scale to millions of clients.',
    category: 'API & Networking',
    difficulty: 'Beginner',
    minutes: 20,
    concepts: ['REST vs GraphQL', 'Pagination', 'Versioning', 'Idempotency'],
    hasContent: false,
    color: '#a78bfa',
  },
  {
    slug: 'grpc-websockets',
    title: 'gRPC & WebSockets',
    description: 'Go beyond REST with binary protocols and persistent connections for real-time and high-performance scenarios.',
    category: 'API & Networking',
    difficulty: 'Intermediate',
    minutes: 25,
    concepts: ['Protobuf', 'Bidirectional streaming', 'Long polling', 'SSE vs WebSocket'],
    hasContent: false,
    color: '#67e8f9',
  },
  {
    slug: 'auth',
    title: 'Auth & Security',
    description: 'Implement secure authentication and authorization: JWTs, OAuth 2.0, API keys, and zero-trust architecture.',
    category: 'API & Networking',
    difficulty: 'Intermediate',
    minutes: 25,
    concepts: ['JWT vs sessions', 'OAuth 2.0', 'mTLS', 'Zero trust'],
    hasContent: false,
    color: '#fb923c',
  },

  // ── Cloud ────────────────────────────────────────────────────
  {
    slug: 'cloud-fundamentals',
    title: 'Cloud Fundamentals',
    description: 'Master IaaS/PaaS/SaaS models, the shared responsibility model, regions vs AZs, elasticity, and the Well-Architected Framework.',
    category: 'Cloud',
    difficulty: 'Beginner',
    minutes: 20,
    concepts: ['IaaS/PaaS/SaaS', 'Shared responsibility', 'Regions & AZs', 'Elasticity'],
    hasContent: true,
    color: '#f97316',
  },
  {
    slug: 'cloud-networking',
    title: 'Cloud Networking',
    description: 'Design secure, scalable cloud networks with VPCs, subnets, security groups, DNS routing policies, and CDN edge caching.',
    category: 'Cloud',
    difficulty: 'Intermediate',
    minutes: 25,
    concepts: ['VPC', 'Subnets', 'Security groups', 'CDN'],
    hasContent: true,
    color: '#3b82f6',
  },
  {
    slug: 'cloud-storage',
    title: 'Cloud Storage',
    description: 'Choose the right storage type — object, block, or file — and understand managed database options, storage tiers, and lifecycle policies.',
    category: 'Cloud',
    difficulty: 'Beginner',
    minutes: 20,
    concepts: ['Object storage', 'Block vs file', 'Storage tiers', 'Lifecycle policies'],
    hasContent: true,
    color: '#10b981',
  },
  {
    slug: 'serverless',
    title: 'Serverless',
    description: 'Build event-driven systems with Lambda, understand cold start mitigation, execution limits, and when serverless beats containers.',
    category: 'Cloud',
    difficulty: 'Intermediate',
    minutes: 25,
    concepts: ['Functions', 'Cold starts', 'Event triggers', 'Limitations'],
    hasContent: true,
    color: '#8b5cf6',
  },
  {
    slug: 'iac',
    title: 'Infrastructure as Code',
    description: 'Eliminate config drift with Terraform and CloudFormation — cover state management, drift detection, and module patterns.',
    category: 'Cloud',
    difficulty: 'Intermediate',
    minutes: 30,
    concepts: ['Terraform', 'Declarative vs imperative', 'State management', 'Drift detection'],
    hasContent: true,
    color: '#06b6d4',
  },
  {
    slug: 'cloud-security',
    title: 'Cloud Security & IAM',
    description: 'Implement zero trust, least-privilege IAM, secrets rotation, encryption at rest and in transit, and VPC security patterns.',
    category: 'Cloud',
    difficulty: 'Advanced',
    minutes: 25,
    concepts: ['Zero trust', 'IAM policies', 'mTLS', 'Secrets management'],
    hasContent: true,
    color: '#ef4444',
  },
]

export const TOPIC_CATEGORIES: TopicCategory[] = ['Distributed Systems', 'Design Patterns', 'API & Networking', 'Cloud']
